name: mah

services:
  gateway:
    build: ../../gateway
    depends_on:
      api:
        condition: service_started
    env_file:
      - ./env/common.env
      - ./env/gateway.env
    restart: unless-stopped
    networks:
      - mahnet

  api:
    build:
      context: ../../backend
      dockerfile: api/Dockerfile
    working_dir: /app
    command: ["/app/entrypoint.sh"]
    expose:
      - "8000"
    env_file:
      - ./env/common.env
      - ./env/api.env
    restart: unless-stopped
    networks:
      - mahnet

  worker:
    build:
      context: ../../backend
      dockerfile: worker/Dockerfile
    working_dir: /app
    entrypoint: ["sh", "/app/entrypoint.sh"]
    env_file:
      - ./env/common.env
      - ./env/worker.env
    restart: unless-stopped
    networks:
      - mahnet

  dispatcher:
    build:
      context: ../../backend
      dockerfile: dispatcher/Dockerfile
    working_dir: /app
    entrypoint: ["sh", "/app/entrypoint.sh"]
    env_file:
      - ./env/common.env
      - ./env/dispatcher.env
    restart: unless-stopped
    networks:
      - mahnet

  scheduler:
    build:
      context: ../../backend
      dockerfile: scheduler/Dockerfile
    working_dir: /app
    entrypoint: ["sh", "/app/entrypoint.sh"]
    env_file:
      - ./env/common.env
      - ./env/scheduler.env
    restart: unless-stopped
    networks:
      - mahnet

  collector:
    build:
      context: ../../backend
      dockerfile: collector/Dockerfile
    working_dir: /app
    entrypoint: ["sh", "/app/entrypoint.sh"]
    env_file:
      - ./env/common.env
      - ./env/collector.env
    restart: unless-stopped
    networks:
      - mahnet

  stream_processor:
    build:
      context: ../../backend
      dockerfile: stream_processor/Dockerfile
    working_dir: /app
    entrypoint: ["sh", "/app/entrypoint.sh"]
    env_file:
      - ./env/common.env
      - ./env/stream_processor.env
    restart: unless-stopped
    networks:
      - mahnet

networks:
  mahnet:
    driver: bridge