"""user_identities 제거 및 OAuth 3-테이블로 재구성: oauth_providers, user_oauth_accounts 생성(토큰 컬럼 제외), 제약/인덱스 추가

Revision ID: 046a68cc9d4e
Revises: 2c6871b8f1f1
Create Date: 2025-11-12 16:05:17.272726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '046a68cc9d4e'
down_revision: Union[str, Sequence[str], None] = '2c6871b8f1f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email_ciphertext',
               existing_type=sa.BLOB(),
               nullable=True)
    op.alter_column('users', 'email_fingerprint',
               existing_type=sa.BINARY(length=32),
               nullable=True)
    op.alter_column('users', 'email_nonce',
               existing_type=sa.BINARY(length=12),
               nullable=True)
    op.alter_column('users', 'email_key_version',
               existing_type=mysql.SMALLINT(),
               nullable=True)
    op.create_unique_constraint(None, 'users', ['email_fingerprint'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'email_key_version',
               existing_type=mysql.SMALLINT(),
               nullable=False)
    op.alter_column('users', 'email_nonce',
               existing_type=sa.BINARY(length=12),
               nullable=False)
    op.alter_column('users', 'email_fingerprint',
               existing_type=sa.BINARY(length=32),
               nullable=False)
    op.alter_column('users', 'email_ciphertext',
               existing_type=sa.BLOB(),
               nullable=False)
    # ### end Alembic commands ###
