"""user_identities 제거 및 OAuth 3-테이블로 재구성: oauth_providers, user_oauth_accounts 생성(토큰 컬럼 제외), 제약/인덱스 추가

Revision ID: 2c6871b8f1f1
Revises: 09b60a935f7c
Create Date: 2025-11-12 15:49:36.453361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2c6871b8f1f1'
down_revision: Union[str, Sequence[str], None] = '09b60a935f7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    ## commands auto generated by Alembic - please adjust! ###
    op.create_table('oauth_providers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('display_name', sa.String(length=64), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('user_oauth_accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('provider_user_id', sa.String(length=128), nullable=False),
    sa.Column('linked_at', sa.DateTime(), nullable=False),
    sa.Column('unlinked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['oauth_providers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_id', 'provider_user_id', name='uq_oauth_provider_uid'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('ix_oauth_user_id', 'user_oauth_accounts', ['user_id'], unique=False)

    # op.drop_index(op.f('ix_user_identities_user_id'), table_name='user_identities')
    # op.drop_index(op.f('uq_identity_provider_uid'), table_name='user_identities')
    op.drop_table('user_identities')
    op.alter_column('outbox_attempts', 'result_payload',
               existing_type=mysql.JSON(),
               nullable=False)
    op.add_column('outboxs', sa.Column('payload', sa.JSON(), nullable=False))
    op.add_column('users', sa.Column('email_ciphertext', sa.LargeBinary(), nullable=False))
    op.add_column('users', sa.Column('email_fingerprint', sa.BINARY(length=32), nullable=False))
    op.add_column('users', sa.Column('email_nonce', sa.BINARY(length=12), nullable=False))
    op.add_column('users', sa.Column('email_key_version', sa.SMALLINT(), nullable=False))
    op.add_column('users', sa.Column('email_verified_at', sa.DateTime(), nullable=True))

    op.create_unique_constraint(None, 'users', ['email_fingerprint'])
    op.drop_column('users', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False))
    op.drop_constraint(None, 'users', type_='unique')

    op.drop_column('users', 'email_verified_at')
    op.drop_column('users', 'email_key_version')
    op.drop_column('users', 'email_nonce')
    op.drop_column('users', 'email_fingerprint')
    op.drop_column('users', 'email_ciphertext')
    op.drop_column('outboxs', 'payload')
    op.alter_column('outbox_attempts', 'result_payload',
               existing_type=mysql.JSON(),
               nullable=True)
    op.create_table('user_identities',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('provider_type', mysql.ENUM('google', 'github', 'kakao', 'naver'), nullable=False),
    sa.Column('provider_user_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128), nullable=False),
    sa.Column('access_token', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=2048), nullable=True),
    sa.Column('refresh_token', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=2048), nullable=True),
    sa.Column('expires_at', mysql.DATETIME(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_identities_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('uq_identity_provider_uid'), 'user_identities', ['provider_type', 'provider_user_id'], unique=True)
    op.create_index(op.f('ix_user_identities_user_id'), 'user_identities', ['user_id'], unique=False)
    op.drop_index('ix_oauth_user_id', table_name='user_oauth_accounts')
    op.drop_table('user_oauth_accounts')
    op.drop_table('oauth_providers')
    # ### end Alembic commands ###
