"""schema: exchange_instruments를 마켓 구조로 확정 (base_asset_id/quote_asset_id FK, uq_market & ix_market_lookup 설정) + 관계 정의 정리

Revision ID: 457634e9ee76
Revises: 70af297a89fa
Create Date: 2025-09-26 18:20:30.961817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '457634e9ee76'
down_revision: Union[str, Sequence[str], None] = '70af297a89fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exchange_instruments', sa.Column('base_asset_id', sa.Integer(), nullable=False))
    op.add_column('exchange_instruments', sa.Column('quote_asset_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_exchange_instruments_base_asset_id'), 'exchange_instruments', ['base_asset_id'], unique=False)
    op.create_index(op.f('ix_exchange_instruments_quote_asset_id'), 'exchange_instruments', ['quote_asset_id'], unique=False)
    # op.drop_index(op.f('ix_exchange_instruments_instrument_id'), table_name='exchange_instruments')
    op.create_index('ix_market_lookup', 'exchange_instruments', ['exchange_id', 'base_asset_id', 'quote_asset_id'], unique=False)
    op.create_unique_constraint('uq_market', 'exchange_instruments', ['exchange_id', 'base_asset_id', 'quote_asset_id'])
    op.drop_constraint(op.f('exchange_instruments_ibfk_2'), 'exchange_instruments', type_='foreignkey')
    op.create_foreign_key(None, 'exchange_instruments', 'instruments', ['quote_asset_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'exchange_instruments', 'instruments', ['base_asset_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('exchange_instruments', 'instrument_id')
    op.drop_column('instruments', 'quote_asset')
    op.drop_column('instruments', 'base_asset')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instruments', sa.Column('base_asset', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32), nullable=False))
    op.add_column('instruments', sa.Column('quote_asset', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32), nullable=False))
    op.add_column('exchange_instruments', sa.Column('instrument_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'exchange_instruments', type_='foreignkey')
    op.drop_constraint(None, 'exchange_instruments', type_='foreignkey')
    op.create_foreign_key(op.f('exchange_instruments_ibfk_2'), 'exchange_instruments', 'instruments', ['instrument_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint('uq_market', 'exchange_instruments', type_='unique')
    op.drop_index('ix_market_lookup', table_name='exchange_instruments')
    op.create_index(op.f('ix_exchange_instruments_instrument_id'), 'exchange_instruments', ['instrument_id'], unique=False)
    op.drop_index(op.f('ix_exchange_instruments_quote_asset_id'), table_name='exchange_instruments')
    op.drop_index(op.f('ix_exchange_instruments_base_asset_id'), table_name='exchange_instruments')
    op.drop_column('exchange_instruments', 'quote_asset_id')
    op.drop_column('exchange_instruments', 'base_asset_id')
    # ### end Alembic commands ###
