"""schema: watchlist_items를 exchange_instrument_id 단일 FK로 전환, created_at 제거, server_default(sort_order=0,is_valid=1) 유지

Revision ID: 59213d179cfe
Revises: 1bfc5f1d8922
Create Date: 2025-09-25 20:33:57.866442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '59213d179cfe'
down_revision: Union[str, Sequence[str], None] = '1bfc5f1d8922'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('watchlist_items', sa.Column('exchange_instrument_id', sa.Integer(), nullable=False))
    # op.drop_index(op.f('ix_watchlist_items_exchange_id'), table_name='watchlist_items')
    # op.drop_index(op.f('ix_watchlist_items_instrument_id'), table_name='watchlist_items')
    op.create_index(op.f('ix_watchlist_items_exchange_instrument_id'), 'watchlist_items', ['exchange_instrument_id'], unique=False)
    op.create_index('ix_wi_user_sort', 'watchlist_items', ['user_id', 'sort_order'], unique=False)
    op.create_unique_constraint('uq_wi_user_exi', 'watchlist_items', ['user_id', 'exchange_instrument_id'])
    op.drop_constraint(op.f('watchlist_items_ibfk_1'), 'watchlist_items', type_='foreignkey')
    op.drop_constraint(op.f('watchlist_items_ibfk_2'), 'watchlist_items', type_='foreignkey')
    op.create_foreign_key(None, 'watchlist_items', 'exchange_instruments', ['exchange_instrument_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('watchlist_items', 'exchange_id')
    op.drop_column('watchlist_items', 'instrument_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('watchlist_items', sa.Column('instrument_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('watchlist_items', sa.Column('exchange_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'watchlist_items', type_='foreignkey')
    op.create_foreign_key(op.f('watchlist_items_ibfk_2'), 'watchlist_items', 'instruments', ['instrument_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('watchlist_items_ibfk_1'), 'watchlist_items', 'exchanges', ['exchange_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint('uq_wi_user_exi', 'watchlist_items', type_='unique')
    op.drop_index('ix_wi_user_sort', table_name='watchlist_items')
    op.drop_index(op.f('ix_watchlist_items_exchange_instrument_id'), table_name='watchlist_items')
    op.create_index(op.f('ix_watchlist_items_instrument_id'), 'watchlist_items', ['instrument_id'], unique=False)
    op.create_index(op.f('ix_watchlist_items_exchange_id'), 'watchlist_items', ['exchange_id'], unique=False)
    op.drop_column('watchlist_items', 'exchange_instrument_id')
    # ### end Alembic commands ###
