"""users, email_verifications, password_resets token_hash byte 타입으로 변경

Revision ID: 5de9c214c252
Revises: 046a68cc9d4e
Create Date: 2025-11-13 21:14:29.944078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5de9c214c252'
down_revision: Union[str, Sequence[str], None] = '046a68cc9d4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('password_resets', 'token_hash',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128),
               type_=sa.BINARY(length=32),
               existing_nullable=False)
    # 1) 임시 BINARY 컬럼 추가 (nullable 허용)
    op.add_column(
        'sessions',
        sa.Column('token_hash_bin', sa.BINARY(32), nullable=True)
    )

    # 2) 기존 hex 문자열 → raw bytes 변환
    #    hex 길이 64 + hex 문자로만 구성된 row만 변환됨
    op.execute("""
        UPDATE sessions
        SET token_hash_bin = UNHEX(token_hash)
        WHERE id>0 AND token_hash IS NOT NULL
          AND LENGTH(token_hash) = 64
          AND token_hash REGEXP '^[0-9A-Fa-f]+$';
    """)

    # 3) 아직 변환 안된 row 있으면 오류 발생시키고 중단
    #    팀원 환경에서 이상한 데이터가 있는지 체크
    # result = op.get_bind().execute(
    #     sa.text("""
    #         SELECT COUNT(*) AS c
    #         FROM sessions
    #         WHERE token_hash IS NOT NULL
    #           AND (token_hash_bin IS NULL)
    #     """)
    # ).fetchone()

    # if result.c != 0:
    #     raise Exception(f"token_hash 변환 실패한 row {result.c}개 → migration 중단")

    # 4) 기존 hex 문자열 컬럼 drop
    op.drop_column('sessions', 'token_hash')

    # 5) 임시 binary 컬럼 rename
    op.alter_column(
        'sessions',
        'token_hash_bin',
        new_column_name='token_hash',
        existing_type=sa.BINARY(32),
        nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'sessions',
        sa.Column('token_hash_str', sa.String(128), nullable=True)
    )

    # bytes → hex
    op.execute("""
        UPDATE sessions
        SET token_hash_str = HEX(token_hash);
    """)

    op.drop_column('sessions', 'token_hash')

    op.alter_column(
        'sessions',
        'token_hash_str',
        new_column_name='token_hash',
        existing_type=sa.String(128),
        nullable=False
    )
    op.alter_column('password_resets', 'token_hash',
               existing_type=sa.BINARY(length=32),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128),
               existing_nullable=False)
    # ### end Alembic commands ###
