"""schema: alert_events를 exchange_instrument_id NULL FK로 전환, alert_id는 RESTRICT로 유지(소프트 삭제 정책)

Revision ID: 70af297a89fa
Revises: f4706728b70c
Create Date: 2025-09-25 21:11:38.199298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '70af297a89fa'
down_revision: Union[str, Sequence[str], None] = 'f4706728b70c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alert_events', 'exchange_instrument_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alert_events', 'exchange_instrument_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
