"""rename is_valid → is_deleted across tables

- Reflects updated naming convention for soft delete flag.
- No data migration required; boolean semantics preserved.
- Queries using "is_valid = 1" should now use "is_deleted = 0".

Revision ID: 78438be647e9
Revises: 61e604a7bf19
Create Date: 2025-10-04 16:49:47.810488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '78438be647e9'
down_revision: Union[str, Sequence[str], None] = '61e604a7bf19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('0'), nullable=False))
    op.add_column('exchange_instruments', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('0'), nullable=False))
    op.add_column('exchanges', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('0'), nullable=False))
    op.add_column('instruments', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('0'), nullable=False))
    op.add_column('user_channels', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('0'), nullable=False))
    op.add_column('users', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('0'), nullable=False))
    op.add_column('watchlist_items', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('0'), nullable=False))

    # 2) 백필: is_valid -> is_deleted (반전해서 복사)
    # MySQL이라면 TRUE/FALSE 대신 1/0 써도 됩니다.
    op.execute("UPDATE alerts              SET is_deleted = CASE WHEN is_valid = 1 THEN 0 ELSE 1 END")
    op.execute("UPDATE exchange_instruments SET is_deleted = CASE WHEN is_valid = 1 THEN 0 ELSE 1 END")
    op.execute("UPDATE exchanges           SET is_deleted = CASE WHEN is_valid = 1 THEN 0 ELSE 1 END")
    op.execute("UPDATE instruments         SET is_deleted = CASE WHEN is_valid = 1 THEN 0 ELSE 1 END")
    op.execute("UPDATE user_channels       SET is_deleted = CASE WHEN is_valid = 1 THEN 0 ELSE 1 END")
    op.execute("UPDATE users               SET is_deleted = CASE WHEN is_valid = 1 THEN 0 ELSE 1 END")
    op.execute("UPDATE watchlist_items     SET is_deleted = CASE WHEN is_valid = 1 THEN 0 ELSE 1 END")


    op.drop_column('alerts', 'is_valid')
    op.drop_column('exchange_instruments', 'is_valid')
    op.drop_column('exchanges', 'is_valid')
    op.drop_column('instruments', 'is_valid')
    op.drop_column('user_channels', 'is_valid')
    op.drop_column('users', 'is_valid')
    op.drop_column('watchlist_items', 'is_valid')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('watchlist_items', sa.Column('is_valid', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('is_valid', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.add_column('user_channels', sa.Column('is_valid', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.add_column('instruments', sa.Column('is_valid', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.add_column('exchanges', sa.Column('is_valid', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.add_column('exchange_instruments', sa.Column('is_valid', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=False))
    op.add_column('alerts', sa.Column('is_valid', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))

    # 2) 백필: is_deleted -> is_valid (다시 반전)
    op.execute("UPDATE alerts              SET is_valid = CASE WHEN is_deleted = 0 THEN 1 ELSE 0 END")
    op.execute("UPDATE exchange_instruments SET is_valid = CASE WHEN is_deleted = 0 THEN 1 ELSE 0 END")
    op.execute("UPDATE exchanges           SET is_valid = CASE WHEN is_deleted = 0 THEN 1 ELSE 0 END")
    op.execute("UPDATE instruments         SET is_valid = CASE WHEN is_deleted = 0 THEN 1 ELSE 0 END")
    op.execute("UPDATE user_channels       SET is_valid = CASE WHEN is_deleted = 0 THEN 1 ELSE 0 END")
    op.execute("UPDATE users               SET is_valid = CASE WHEN is_deleted = 0 THEN 1 ELSE 0 END")
    op.execute("UPDATE watchlist_items     SET is_valid = CASE WHEN is_deleted = 0 THEN 1 ELSE 0 END")


    op.drop_column('watchlist_items', 'is_deleted')
    op.drop_column('users', 'is_deleted')
    op.drop_column('user_channels', 'is_deleted')
    op.drop_column('instruments', 'is_deleted')
    op.drop_column('exchanges', 'is_deleted')
    op.drop_column('exchange_instruments', 'is_deleted')
    op.drop_column('alerts', 'is_deleted')
    # ### end Alembic commands ###
