"""modify exchanges, instruments, exchange_instruments table
update column status to is_active 
add column create_at, update_at, is_valid

Revision ID: 87294fe503ce
Revises: 380f86d46c7d
Create Date: 2025-09-25 19:29:35.324167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '87294fe503ce'
down_revision: Union[str, Sequence[str], None] = '380f86d46c7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exchange_instruments', 'is_active',
               existing_type=mysql.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('exchanges', 'is_active',
               existing_type=mysql.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('instruments', 'is_active',
               existing_type=mysql.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('instruments', 'is_active',
               existing_type=sa.Boolean(),
               type_=mysql.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('exchanges', 'is_active',
               existing_type=sa.Boolean(),
               type_=mysql.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('exchange_instruments', 'is_active',
               existing_type=sa.Boolean(),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
