"""modify exchanges, instruments, exchange_instruments table
update column status to is_active 
add column create_at, update_at, is_valid

Revision ID: e01bbdd0a4d8
Revises: 87294fe503ce
Create Date: 2025-09-25 19:30:16.989356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e01bbdd0a4d8'
down_revision: Union[str, Sequence[str], None] = '87294fe503ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
