"""id 값 Integer, user_oauth_accounts.provider_id를 oauth_providers_id로  naming change

Revision ID: e2c04b5d6cb7
Revises: fe63fdb7ea7a
Create Date: 2025-12-07 15:46:55.404690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e2c04b5d6cb7'
down_revision: Union[str, Sequence[str], None] = 'fe63fdb7ea7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "outbox_attempts_ibfk_1",
        "outbox_attempts",
        type_="foreignkey",
    )
    op.alter_column('outbox_attempts', 'outbox_id',
               existing_type=mysql.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('outboxs', 'id',
               existing_type=mysql.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('outboxs', 'aggregate_id',
               existing_type=mysql.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.create_foreign_key(
        "outbox_attempts_ibfk_1",
        "outbox_attempts",
        "outboxs",
        ["outbox_id"],
        ["id"],
    )
    op.add_column('user_oauth_accounts', sa.Column('oauth_providers_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('user_oauth_accounts_ibfk_1'), 'user_oauth_accounts', type_='foreignkey')
    op.drop_constraint(op.f('uq_oauth_provider_uid'), 'user_oauth_accounts', type_='unique')
    op.create_unique_constraint('uq_oauth_provider_uid', 'user_oauth_accounts', ['oauth_providers_id', 'provider_user_id'])
    op.create_foreign_key(None, 'user_oauth_accounts', 'oauth_providers', ['oauth_providers_id'], ['id'])
    op.drop_column('user_oauth_accounts', 'provider_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_oauth_accounts', sa.Column('provider_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user_oauth_accounts', type_='foreignkey')
    op.create_foreign_key(op.f('user_oauth_accounts_ibfk_1'), 'user_oauth_accounts', 'oauth_providers', ['provider_id'], ['id'])
    op.drop_constraint('uq_oauth_provider_uid', 'user_oauth_accounts', type_='unique')
    op.create_unique_constraint(op.f('uq_oauth_provider_uid'), 'user_oauth_accounts', ['provider_id', 'provider_user_id'])
    op.drop_column('user_oauth_accounts', 'oauth_providers_id')

    # ### end Alembic commands ###