"""add users table
add index to price_snapshots
rename column is_active to status
drop legacy tables

Revision ID: ecc45068254e
Revises: 7f9af87fd032
Create Date: 2025-09-25 15:04:01.708399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ecc45068254e'
down_revision: Union[str, Sequence[str], None] = '7f9af87fd032'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_snapshots_1d',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exchange_id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('ts_open', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.DECIMAL(precision=32, scale=16), nullable=False),
    sa.Column('high', sa.DECIMAL(precision=32, scale=16), nullable=False),
    sa.Column('low', sa.DECIMAL(precision=32, scale=16), nullable=False),
    sa.Column('close', sa.DECIMAL(precision=32, scale=16), nullable=False),
    sa.Column('volume', sa.DECIMAL(precision=32, scale=16), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['exchange_id'], ['exchanges.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exchange_id', 'instrument_id', 'ts_open', name='uq_price_1d_key')
    )
    op.create_index('ix_price_1d_bucket', 'price_snapshots_1d', ['ts_open'], unique=False)
    op.create_index('ix_price_1d_instr_bucket', 'price_snapshots_1d', ['instrument_id', 'ts_open'], unique=False)
    op.create_table('price_snapshots_1h',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exchange_id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('ts_open', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.DECIMAL(precision=32, scale=16), nullable=False),
    sa.Column('high', sa.DECIMAL(precision=32, scale=16), nullable=False),
    sa.Column('low', sa.DECIMAL(precision=32, scale=16), nullable=False),
    sa.Column('close', sa.DECIMAL(precision=32, scale=16), nullable=False),
    sa.Column('volume', sa.DECIMAL(precision=32, scale=16), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['exchange_id'], ['exchanges.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exchange_id', 'instrument_id', 'ts_open', name='uq_price_1h_key')
    )
    op.create_index('ix_price_1h_bucket', 'price_snapshots_1h', ['ts_open'], unique=False)
    op.create_index('ix_price_1h_instr_bucket', 'price_snapshots_1h', ['instrument_id', 'ts_open'], unique=False)
    # FK 컬럼과 동일한 prefix로 '대체 인덱스'를 먼저 만든다
    op.create_index('ix_prices_latest_instrument_id', 'prices_latest', ['instrument_id'], unique=False)
    op.drop_index(op.f('ix_prices_latest_instrument'), table_name='prices_latest')
    op.drop_index(op.f('ix_prices_latest_ts'), table_name='prices_latest')
    op.drop_table('prices_latest')
    op.add_column('exchange_instruments', sa.Column('is_active', sa.Integer(), nullable=False))
    op.drop_column('exchange_instruments', 'active')
    op.add_column('price_snapshots_1m', sa.Column('ts_open', sa.DateTime(timezone=True), nullable=False))
    op.add_column('price_snapshots_1m', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.drop_index(op.f('ix_price_1m_bucket'), table_name='price_snapshots_1m')
    op.create_index('ix_price_1m_bucket', 'price_snapshots_1m', ['ts_open'], unique=False)
    # FK가 걸린 컬럼을 단독으로 인덱싱
    op.create_index('ix_price_1m_instrument_id', 'price_snapshots_1m', ['instrument_id'], unique=False)
    op.drop_index(op.f('ix_price_1m_instr_bucket'), table_name='price_snapshots_1m')
    op.create_index('ix_price_1m_instr_bucket', 'price_snapshots_1m', ['instrument_id', 'ts_open'], unique=False)

    op.create_unique_constraint('uq_price_1m_key_tmp', 'price_snapshots_1m', ['exchange_id', 'instrument_id'])
    op.drop_constraint(op.f('uq_price_1m_key'), 'price_snapshots_1m', type_='unique')
    op.create_unique_constraint('uq_price_1m_key', 'price_snapshots_1m', ['exchange_id', 'instrument_id', 'ts_open'])
    op.drop_constraint('uq_price_1m_key_tmp', 'price_snapshots_1m', type_='unique')
    
    op.drop_column('price_snapshots_1m', 'bucket_minute')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price_snapshots_1m', sa.Column('bucket_minute', mysql.DATETIME(), nullable=False))

    op.create_unique_constraint('uq_price_1m_key_tmp', 'price_snapshots_1m', ['exchange_id', 'instrument_id'])
    op.drop_constraint('uq_price_1m_key', 'price_snapshots_1m', type_='unique')
    op.create_unique_constraint(op.f('uq_price_1m_key'), 'price_snapshots_1m', ['exchange_id', 'instrument_id', 'bucket_minute'])
    op.drop_constraint('uq_price_1m_key_tmp', 'price_snapshots_1m', type_='unique')

    op.drop_index('ix_price_1m_instr_bucket', table_name='price_snapshots_1m')
    op.create_index(op.f('ix_price_1m_instr_bucket'), 'price_snapshots_1m', ['instrument_id', 'bucket_minute'], unique=False)
    op.drop_index('ix_price_1m_instrument_id', table_name='price_snapshots_1m')
    op.drop_index('ix_price_1m_bucket', table_name='price_snapshots_1m')
    op.create_index(op.f('ix_price_1m_bucket'), 'price_snapshots_1m', ['bucket_minute'], unique=False)
    op.drop_column('price_snapshots_1m', 'updated_at')
    op.drop_column('price_snapshots_1m', 'ts_open')
    op.add_column('exchange_instruments', sa.Column('active', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('exchange_instruments', 'is_active')
    op.create_table('prices_latest',
    sa.Column('exchange_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('instrument_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('last_price', mysql.DECIMAL(precision=32, scale=16), nullable=False),
    sa.Column('volume_24h', mysql.DECIMAL(precision=32, scale=16), nullable=True),
    sa.Column('high_24h', mysql.DECIMAL(precision=32, scale=16), nullable=True),
    sa.Column('low_24h', mysql.DECIMAL(precision=32, scale=16), nullable=True),
    sa.Column('ts', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['exchange_id'], ['exchanges.id'], name=op.f('prices_latest_ibfk_1'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], name=op.f('prices_latest_ibfk_2'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('exchange_id', 'instrument_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_prices_latest_ts'), 'prices_latest', ['ts'], unique=False)
    op.create_index(op.f('ix_prices_latest_instrument'), 'prices_latest', ['instrument_id'], unique=False)
    op.drop_index('ix_prices_latest_instrument_id', table_name='prices_latest')
    op.drop_index('ix_price_1h_instr_bucket', table_name='price_snapshots_1h')
    op.drop_index('ix_price_1h_bucket', table_name='price_snapshots_1h')
    op.drop_table('price_snapshots_1h')
    op.drop_index('ix_price_1d_instr_bucket', table_name='price_snapshots_1d')
    op.drop_index('ix_price_1d_bucket', table_name='price_snapshots_1d')
    op.drop_table('price_snapshots_1d')
    # ### end Alembic commands ###
