"""add is_valid to core/user-owned tables

Revision ID: eec5d47a8473
Revises: 5259e957988c
Create Date: 2025-09-22 14:12:28.697697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eec5d47a8473'
down_revision: Union[str, Sequence[str], None] = '5259e957988c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('is_valid', sa.Boolean(), nullable=False))
    op.add_column('exchanges', sa.Column('is_valid', sa.Boolean(), nullable=False))
    op.add_column('instruments', sa.Column('is_valid', sa.Boolean(), nullable=False))
    op.add_column('user_channels', sa.Column('is_valid', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('is_valid', sa.Boolean(), nullable=False))
    op.add_column('watchlist_items', sa.Column('is_valid', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('watchlist_items', 'is_valid')
    op.drop_column('users', 'is_valid')
    op.drop_column('user_channels', 'is_valid')
    op.drop_column('instruments', 'is_valid')
    op.drop_column('exchanges', 'is_valid')
    op.drop_column('alerts', 'is_valid')
    # ### end Alembic commands ###
