"""email_verifications table status 값 추가

Revision ID: f76aae632c99
Revises: e2c04b5d6cb7
Create Date: 2025-12-16 17:42:54.203657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f76aae632c99'
down_revision: Union[str, Sequence[str], None] = 'e2c04b5d6cb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('outbox_attempts_ibfk_1'), 'outbox_attempts', type_='foreignkey')
    op.create_foreign_key(None, 'outbox_attempts', 'outboxs', ['outbox_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'outbox_attempts', type_='foreignkey')
    op.create_foreign_key(op.f('outbox_attempts_ibfk_1'), 'outbox_attempts', 'outboxs', ['outbox_id'], ['id'])
    # ### end Alembic commands ###
