from typing import Protocol, Optional, List
from app.infra.db.model import Alert 

class AlertRepo(Protocol):
    def add(self, user_id: int, data) -> Alert: ...
    def list_by_user(self, user_id: int) -> List[Alert]: ...
    def delete(self, user_id: int, alert_id: int) -> None: ...
    def get(self, user_id: int, alert_id: int) -> Optional[Alert]: ...
