from typing import Protocol, Optional, List
from app.infra.db.model import AlertModel

class AlertRepo(Protocol):
    def add(self, user_id: int, *, exchange_id: int, symbol: str,
           target_price: float, direction: str) -> AlertModel: ...
    def list_by_user(self, user_id: int) -> List[AlertModel]: ...
    def delete(self, user_id: int, alert_id: int) -> None: ...
    def get(self, user_id: int, alert_id: int) -> Optional[AlertModel]: ...
