from typing import Protocol, Optional
from app.infra.db.model import User as UserModel

class UserRepo(Protocol):

    def add(self, user: UserModel) -> UserModel: ...
    def get_by_email(self, email: str) -> UserModel | None: ...
    def get_by_id(self, user_id: int) -> Optional[UserModel]: ...
