from typing import Protocol, Sequence, Tuple
from app.infra.db.model import WatchlistItemModel

class WatchlistRepo(Protocol):
    def list(self, *, user_id: int, limit: int, offset: int, is_asc: bool) -> Sequence[WatchlistItemModel]: ...
    def exists(self, *, user_id: int, exchange_instrument_id: int) -> bool: ...
    def mapping_exists(self, *, exchange_instrument_id: int) -> bool: ...
    def next_sort_order(self, *, user_id: int) -> int: ...
    def create(self, *, user_id: int, exchange_instrument_id: int, sort_order: int) -> WatchlistItemModel: ...
    def get_by_id(self, *, item_id: int, user_id: int) -> WatchlistItemModel: ...
    def pick_display_fields(self, row: WatchlistItemModel) -> Tuple[str, str, str]: ...
