from typing import Protocol
from .dto import OAuthIdentity


class KakaoOAuth(Protocol):
    def build_authorize_path(self, state: str) -> str: ...
    def fetch_identity(self, code: str) -> OAuthIdentity: ...
    def unlink(self, provider_user_id: int) -> None: ...
