from typing import Protocol

from app.infra.db.repository.protocol.aio.alert_repo import AlertRepo

class AsyncUnitOfWork(Protocol):
    async def __aenter__(self): ...
    async def __aexit__(self, exc_type, exc, tb) -> bool: ...

    async def commit(self) -> None: ...
    async def rollback(self) -> None: ...
    async def flush(self) -> None: ...

    @property
    def alerts(self) -> AlertRepo: ...