from typing import Protocol, runtime_checkable, Self
from app.infra.db.repository.protocol.session_repo import SessionRepo
from app.infra.db.repository.protocol.market_repo import MarketRepo
from app.infra.db.repository.protocol.watchlist_repo import WatchlistRepo
from app.infra.db.repository.protocol.channel_repo import ChannelRepo
from app.infra.db.repository.protocol.provider_repo import ProviderRepo
from app.infra.db.repository.protocol.alert_repo import AlertRepo
from app.infra.db.repository.protocol.user_repo import UserRepo
from app.infra.db.repository.protocol.outbox_repo import OutboxRepo
from app.infra.db.repository.protocol.support_repo import SupportRepo

@runtime_checkable
class UnitOfWork(Protocol):

    def commit(self) -> None: ...
    def commit_outbox_idempotent(self) -> None: ...
    def rollback(self) -> None: ...
    def flush(self) -> None: ...

    def __enter__(self) -> Self: ...
    def __exit__(self, exc_type, *_) -> bool | None: ...

    @property
    def users(self) -> UserRepo: ...
    @property
    def sessions(self) -> SessionRepo: ...
    @property
    def alerts(self) -> AlertRepo: ...
    @property
    def markets(self) -> MarketRepo: ...
    @property
    def watchlists(self) -> WatchlistRepo: ...
    @property
    def channels(self) -> ChannelRepo: ...
    @property
    def providers(self) -> ProviderRepo: ...
    @property
    def outboxs(self) -> OutboxRepo: ...
    @property
    def supports(self) -> SupportRepo: ...
