
export enum BridgeType {
  THEME = 'THEME',
  KEEP_SCREEN_ON = 'KEEP_SCREEN_ON',
  NOTIFICATION_SOUND = 'NOTIFICATION_SOUND',
  VIBRATE = 'VIBRATE',
  AUTH_LOGIN = 'AUTH_LOGIN',
  AUTH_LOGOUT = 'AUTH_LOGOUT',
}
