FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_DISABLE_PIP_VERSION_CHECK=1 \
    PIP_NO_CACHE_DIR=1 \
    TZ=${TZ:-Asia/Seoul}
    
WORKDIR /app

COPY common/requirements.txt .
RUN pip install --upgrade pip && pip install -r /app/requirements.txt
