"""watchlist_items, exchange_instruments, exchanges, instruments 테이블 변경 is_deleted → deleted_at

Revision ID: 013279996319
Revises: 508aee8b7751
Create Date: 2026-03-13 19:08:21.093548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '013279996319'
down_revision: Union[str, Sequence[str], None] = '508aee8b7751'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exchange_instruments', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('exchange_instruments', 'is_deleted')
    op.add_column('exchanges', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('exchanges', 'is_deleted')
    op.add_column('instruments', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('instruments', 'is_deleted')
    op.add_column('watchlist_items', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('watchlist_items', 'is_deleted')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('watchlist_items', sa.Column('is_deleted', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False))
    op.drop_column('watchlist_items', 'deleted_at')
    op.add_column('instruments', sa.Column('is_deleted', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False))
    op.drop_column('instruments', 'deleted_at')
    op.add_column('exchanges', sa.Column('is_deleted', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False))
    op.drop_column('exchanges', 'deleted_at')
    op.add_column('exchange_instruments', sa.Column('is_deleted', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False))
    op.drop_column('exchange_instruments', 'deleted_at')
    # ### end Alembic commands ###
