"""alert_types add column sort_order

Revision ID: 0163edcdcee8
Revises: c3f740afa293
Create Date: 2026-05-05 21:19:31.941818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0163edcdcee8'
down_revision: Union[str, Sequence[str], None] = 'c3f740afa293'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alert_types', sa.Column('sort_order', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alert_types', 'sort_order')
    # ### end Alembic commands ###
