"""user_channels 테이블 (channel_provider_id, user_id, address) 복합 유니크 인덱스 및 조회용 인덱스 추가

Revision ID: 02a6b92df221
Revises: b412adcdc797
Create Date: 2026-04-19 23:24:06.488799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02a6b92df221'
down_revision: Union[str, Sequence[str], None] = 'b412adcdc797'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_channel_address_provider', 'user_channels', ['channel_provider_id', 'address'], unique=False)
    op.create_index('ix_user_channel_user_provider', 'user_channels', ['user_id', 'channel_provider_id'], unique=False)
    op.create_unique_constraint('uq_user_channel_provider_user_address', 'user_channels', ['channel_provider_id', 'user_id', 'address'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_channel_provider_user_address', 'user_channels', type_='unique')
    op.drop_index('ix_user_channel_user_provider', table_name='user_channels')
    op.drop_index('ix_user_channel_address_provider', table_name='user_channels')
    # ### end Alembic commands ###
