"""add table outbox_attempts, alert table outboxs

Revision ID: 09b60a935f7c
Revises: 6ef315795444
Create Date: 2025-10-20 15:45:12.899448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09b60a935f7c'
down_revision: Union[str, Sequence[str], None] = '6ef315795444'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outbox_attempts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('outbox_id', sa.BigInteger(), nullable=False),
    sa.Column('attempt_no', sa.Integer(), nullable=False),
    sa.Column('success', sa.Integer(), nullable=False),
    sa.Column('retryable', sa.Integer(), nullable=False),
    sa.Column('result_code', sa.String(length=64), nullable=True),
    sa.Column('result_message', sa.Text(), nullable=True),
    sa.Column('result_payload', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['outbox_id'], ['outboxs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_attempts_outbox_time', 'outbox_attempts', ['outbox_id', 'started_at'], unique=False)
    op.create_index(op.f('ix_outbox_attempts_outbox_id'), 'outbox_attempts', ['outbox_id'], unique=False)
    op.create_index('ux_outbox_attempt', 'outbox_attempts', ['outbox_id', 'attempt_no'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ux_outbox_attempt', table_name='outbox_attempts')
    op.drop_index(op.f('ix_outbox_attempts_outbox_id'), table_name='outbox_attempts')
    op.drop_index('ix_attempts_outbox_time', table_name='outbox_attempts')
    op.drop_table('outbox_attempts')
    # ### end Alembic commands ###
