"""refactor: price_snapshots_* 테이블을 exchange_instrument_id 기반으로 변경 (exchange_id/instrument_id 제거)

Revision ID: 1bfc5f1d8922
Revises: e01bbdd0a4d8
Create Date: 2025-09-25 19:56:41.983155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1bfc5f1d8922'
down_revision: Union[str, Sequence[str], None] = 'e01bbdd0a4d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price_snapshots_1d', sa.Column('exchange_instrument_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_price_1d_bucket'), table_name='price_snapshots_1d')
    # 임시 인덱스 추가
    op.create_index(op.f("ix_price_1d_instr_id_tmp"), "price_snapshots_1d", ["instrument_id"], unique=False)
    op.drop_index(op.f('ix_price_1d_instr_bucket'), table_name='price_snapshots_1d')
    # 임시 인덱스 추가
    op.create_index(op.f("ix_price_1d_exch_id_tmp"), "price_snapshots_1d", ["exchange_id"], unique=False)
    op.drop_index(op.f('uq_price_1d_key'), table_name='price_snapshots_1d')
    op.create_index('ix_price_1d_exi_ts', 'price_snapshots_1d', ['exchange_instrument_id', 'ts_open'], unique=False)
    op.create_index(op.f('ix_price_snapshots_1d_exchange_instrument_id'), 'price_snapshots_1d', ['exchange_instrument_id'], unique=False)
    op.create_unique_constraint('uq_price_1d_exi_ts', 'price_snapshots_1d', ['exchange_instrument_id', 'ts_open'])
    op.drop_constraint(op.f('price_snapshots_1d_ibfk_2'), 'price_snapshots_1d', type_='foreignkey')
    op.drop_constraint(op.f('price_snapshots_1d_ibfk_1'), 'price_snapshots_1d', type_='foreignkey')
    op.create_foreign_key(None, 'price_snapshots_1d', 'exchange_instruments', ['exchange_instrument_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('price_snapshots_1d', 'instrument_id')
    op.drop_column('price_snapshots_1d', 'exchange_id')
    op.add_column('price_snapshots_1h', sa.Column('exchange_instrument_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_price_1h_bucket'), table_name='price_snapshots_1h')
    # 임시 인덱스 추가
    op.create_index(op.f("ix_price_1h_instr_id_tmp"), "price_snapshots_1h", ["instrument_id"], unique=False)
    op.drop_index(op.f('ix_price_1h_instr_bucket'), table_name='price_snapshots_1h')
    # 임시 인덱스 추가
    op.create_index(op.f("ix_price_1h_exch_id_tmp"), "price_snapshots_1h", ["exchange_id"], unique=False)
    op.drop_index(op.f('uq_price_1h_key'), table_name='price_snapshots_1h')
    op.create_index('ix_price_1h_exi_ts', 'price_snapshots_1h', ['exchange_instrument_id', 'ts_open'], unique=False)
    op.create_index(op.f('ix_price_snapshots_1h_exchange_instrument_id'), 'price_snapshots_1h', ['exchange_instrument_id'], unique=False)
    op.create_unique_constraint('uq_price_1h_exi_ts', 'price_snapshots_1h', ['exchange_instrument_id', 'ts_open'])
    op.drop_constraint(op.f('price_snapshots_1h_ibfk_1'), 'price_snapshots_1h', type_='foreignkey')
    op.drop_constraint(op.f('price_snapshots_1h_ibfk_2'), 'price_snapshots_1h', type_='foreignkey')
    op.create_foreign_key(None, 'price_snapshots_1h', 'exchange_instruments', ['exchange_instrument_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('price_snapshots_1h', 'instrument_id')
    op.drop_column('price_snapshots_1h', 'exchange_id')
    op.add_column('price_snapshots_1m', sa.Column('exchange_instrument_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_price_1m_bucket'), table_name='price_snapshots_1m')
    # 임시 인덱스 추가
    op.create_index(op.f("ix_price_1m_instr_id_tmp"), "price_snapshots_1m", ["instrument_id"], unique=False)
    op.drop_index(op.f('ix_price_1m_instr_bucket'), table_name='price_snapshots_1m')
    # 임시 인덱스 추가
    op.create_index(op.f("ix_price_1m_exch_id_tmp"), "price_snapshots_1m", ["exchange_id"], unique=False)
    op.drop_index(op.f('uq_price_1m_key'), table_name='price_snapshots_1m')
    op.create_index('ix_price_1m_exi_ts', 'price_snapshots_1m', ['exchange_instrument_id', 'ts_open'], unique=False)
    op.create_index(op.f('ix_price_snapshots_1m_exchange_instrument_id'), 'price_snapshots_1m', ['exchange_instrument_id'], unique=False)
    op.create_unique_constraint('uq_price_1m_exi_ts', 'price_snapshots_1m', ['exchange_instrument_id', 'ts_open'])
    op.drop_constraint(op.f('price_snapshots_1m_ibfk_2'), 'price_snapshots_1m', type_='foreignkey')
    op.drop_constraint(op.f('price_snapshots_1m_ibfk_1'), 'price_snapshots_1m', type_='foreignkey')
    op.create_foreign_key(None, 'price_snapshots_1m', 'exchange_instruments', ['exchange_instrument_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('price_snapshots_1m', 'instrument_id')
    op.drop_column('price_snapshots_1m', 'exchange_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price_snapshots_1m', sa.Column('exchange_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('price_snapshots_1m', sa.Column('instrument_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'price_snapshots_1m', type_='foreignkey')
    op.create_foreign_key(op.f('price_snapshots_1m_ibfk_1'), 'price_snapshots_1m', 'exchanges', ['exchange_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('price_snapshots_1m_ibfk_2'), 'price_snapshots_1m', 'instruments', ['instrument_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint('uq_price_1m_exi_ts', 'price_snapshots_1m', type_='unique')
    op.drop_index(op.f('ix_price_snapshots_1m_exchange_instrument_id'), table_name='price_snapshots_1m')
    op.drop_index('ix_price_1m_exi_ts', table_name='price_snapshots_1m')
    op.create_index(op.f('uq_price_1m_key'), 'price_snapshots_1m', ['exchange_id', 'instrument_id', 'ts_open'], unique=True)
    op.create_index(op.f('ix_price_1m_instr_bucket'), 'price_snapshots_1m', ['instrument_id', 'ts_open'], unique=False)
    op.create_index(op.f('ix_price_1m_bucket'), 'price_snapshots_1m', ['ts_open'], unique=False)
    op.drop_column('price_snapshots_1m', 'exchange_instrument_id')
    op.add_column('price_snapshots_1h', sa.Column('exchange_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('price_snapshots_1h', sa.Column('instrument_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'price_snapshots_1h', type_='foreignkey')
    op.create_foreign_key(op.f('price_snapshots_1h_ibfk_2'), 'price_snapshots_1h', 'instruments', ['instrument_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('price_snapshots_1h_ibfk_1'), 'price_snapshots_1h', 'exchanges', ['exchange_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint('uq_price_1h_exi_ts', 'price_snapshots_1h', type_='unique')
    op.drop_index(op.f('ix_price_snapshots_1h_exchange_instrument_id'), table_name='price_snapshots_1h')
    op.drop_index('ix_price_1h_exi_ts', table_name='price_snapshots_1h')
    op.create_index(op.f('uq_price_1h_key'), 'price_snapshots_1h', ['exchange_id', 'instrument_id', 'ts_open'], unique=True)
    op.create_index(op.f('ix_price_1h_instr_bucket'), 'price_snapshots_1h', ['instrument_id', 'ts_open'], unique=False)
    op.create_index(op.f('ix_price_1h_bucket'), 'price_snapshots_1h', ['ts_open'], unique=False)
    op.drop_column('price_snapshots_1h', 'exchange_instrument_id')
    op.add_column('price_snapshots_1d', sa.Column('exchange_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('price_snapshots_1d', sa.Column('instrument_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'price_snapshots_1d', type_='foreignkey')
    op.create_foreign_key(op.f('price_snapshots_1d_ibfk_1'), 'price_snapshots_1d', 'exchanges', ['exchange_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('price_snapshots_1d_ibfk_2'), 'price_snapshots_1d', 'instruments', ['instrument_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint('uq_price_1d_exi_ts', 'price_snapshots_1d', type_='unique')
    op.drop_index(op.f('ix_price_snapshots_1d_exchange_instrument_id'), table_name='price_snapshots_1d')
    op.drop_index('ix_price_1d_exi_ts', table_name='price_snapshots_1d')
    op.create_index(op.f('uq_price_1d_key'), 'price_snapshots_1d', ['exchange_id', 'instrument_id', 'ts_open'], unique=True)
    op.create_index(op.f('ix_price_1d_instr_bucket'), 'price_snapshots_1d', ['instrument_id', 'ts_open'], unique=False)
    op.create_index(op.f('ix_price_1d_bucket'), 'price_snapshots_1d', ['ts_open'], unique=False)
    op.drop_column('price_snapshots_1d', 'exchange_instrument_id')
    # ### end Alembic commands ###
