"""alert_types scope data type modify

Revision ID: 1d5869f297ff
Revises: 0163edcdcee8
Create Date: 2026-05-06 20:16:03.710387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1d5869f297ff'
down_revision: Union[str, Sequence[str], None] = '0163edcdcee8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alert_types', 'scope',
               existing_type=mysql.ENUM('single', 'cross', collation='utf8mb4_unicode_ci'),
               type_=sa.String(length=32),
               existing_nullable=False,
               existing_server_default=sa.text("'single'"))
    op.drop_column('alerts', 'period')
    op.drop_column('alerts', 'timeframe')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('timeframe', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=16), nullable=True))
    op.add_column('alerts', sa.Column('period', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('alert_types', 'scope',
               existing_type=sa.String(length=32),
               type_=mysql.ENUM('single', 'cross', collation='utf8mb4_unicode_ci'),
               existing_nullable=False,
               existing_server_default=sa.text("'single'"))
    # ### end Alembic commands ###
