"""notice column add summary

Revision ID: 2759784518f4
Revises: e3ce33e2e98b
Create Date: 2026-04-07 13:51:11.706964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2759784518f4'
down_revision: Union[str, Sequence[str], None] = 'e3ce33e2e98b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notices', sa.Column('summary', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notices', 'summary')
    # ### end Alembic commands ###
