"""alert events table drop column queued_at

Revision ID: 31c8b45c0a02
Revises: a3d6e20ff230
Create Date: 2026-05-13 15:12:10.465247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '31c8b45c0a02'
down_revision: Union[str, Sequence[str], None] = 'a3d6e20ff230'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alert_events', 'queued_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alert_events', sa.Column('queued_at', mysql.DATETIME(), nullable=True))
    # ### end Alembic commands ###
