"""schema: alert_events를 exchange_instrument_id NOT NULL FK로 전환, alert_id는 RESTRICT로 유지(소프트 삭제 정책)

Revision ID: 339e8141ec1a
Revises: ba15068e02c6
Create Date: 2025-09-25 21:09:23.591547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '339e8141ec1a'
down_revision: Union[str, Sequence[str], None] = 'ba15068e02c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alert_events', sa.Column('exchange_instrument_id', sa.Integer(), nullable=False))
    # op.drop_index(op.f('ix_alert_events_exchange_id'), table_name='alert_events')
    # op.drop_index(op.f('ix_alert_events_instrument_id'), table_name='alert_events')
    op.create_index(op.f('ix_alert_events_exchange_instrument_id'), 'alert_events', ['exchange_instrument_id'], unique=False)
    op.drop_constraint(op.f('alert_events_ibfk_3'), 'alert_events', type_='foreignkey')
    op.drop_constraint(op.f('alert_events_ibfk_2'), 'alert_events', type_='foreignkey')
    op.drop_constraint(op.f('alert_events_ibfk_1'), 'alert_events', type_='foreignkey')
    op.create_foreign_key(None, 'alert_events', 'alerts', ['alert_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'alert_events', 'exchange_instruments', ['exchange_instrument_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('alert_events', 'exchange_id')
    op.drop_column('alert_events', 'instrument_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alert_events', sa.Column('instrument_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('alert_events', sa.Column('exchange_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'alert_events', type_='foreignkey')
    op.drop_constraint(None, 'alert_events', type_='foreignkey')
    op.create_foreign_key(op.f('alert_events_ibfk_1'), 'alert_events', 'alerts', ['alert_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('alert_events_ibfk_2'), 'alert_events', 'exchanges', ['exchange_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('alert_events_ibfk_3'), 'alert_events', 'instruments', ['instrument_id'], ['id'], ondelete='RESTRICT')
    op.drop_index(op.f('ix_alert_events_exchange_instrument_id'), table_name='alert_events')
    op.create_index(op.f('ix_alert_events_instrument_id'), 'alert_events', ['instrument_id'], unique=False)
    op.create_index(op.f('ix_alert_events_exchange_id'), 'alert_events', ['exchange_id'], unique=False)
    op.drop_column('alert_events', 'exchange_instrument_id')
    # ### end Alembic commands ###
