"""update news item fingerprints

Revision ID: 346444b603f1
Revises: e54a225d4d81
Create Date: 2026-05-19 19:52:01.290675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '346444b603f1'
down_revision: Union[str, Sequence[str], None] = 'e54a225d4d81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_items', sa.Column('title_fingerprint', sa.BINARY(length=32), nullable=False))
    op.add_column('news_items', sa.Column('link_fingerprint', sa.BINARY(length=32), nullable=False))
    op.add_column('news_items', sa.Column('content_fingerprint', sa.BINARY(length=32), nullable=True))
    op.drop_index(op.f('ix_news_item_source_link_hash'), table_name='news_items')
    op.drop_index(op.f('ix_news_item_source_title_hash'), table_name='news_items')
    op.create_index('ix_news_item_source_link_fp', 'news_items', ['rss_source_id', 'link_fingerprint'], unique=True)
    op.create_index('ix_news_item_source_title_fp', 'news_items', ['rss_source_id', 'title_fingerprint'], unique=False)
    op.drop_column('news_items', 'content_hash')
    op.drop_column('news_items', 'link_hash')
    op.drop_column('news_items', 'title_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_items', sa.Column('title_hash', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64), nullable=False))
    op.add_column('news_items', sa.Column('link_hash', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64), nullable=False))
    op.add_column('news_items', sa.Column('content_hash', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64), nullable=True))
    op.drop_index('ix_news_item_source_title_fp', table_name='news_items')
    op.drop_index('ix_news_item_source_link_fp', table_name='news_items')
    op.create_index(op.f('ix_news_item_source_title_hash'), 'news_items', ['rss_source_id', 'title_hash'], unique=False)
    op.create_index(op.f('ix_news_item_source_link_hash'), 'news_items', ['rss_source_id', 'link_hash'], unique=True)
    op.drop_column('news_items', 'content_fingerprint')
    op.drop_column('news_items', 'link_fingerprint')
    op.drop_column('news_items', 'title_fingerprint')
    # ### end Alembic commands ###
