"""oauth_providers 칼럼명 수정 enabled -> is_active

Revision ID: 350765503d12
Revises: 8e58b1e22c7f
Create Date: 2026-03-02 13:48:13.360601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '350765503d12'
down_revision: Union[str, Sequence[str], None] = '8e58b1e22c7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
