"""modify exchanges, instruments, exchange_instruments table
update column status to is_active 
add column create_at, update_at, is_valid

Revision ID: 380f86d46c7d
Revises: 6e1de10f5901
Create Date: 2025-09-25 19:24:55.448619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '380f86d46c7d'
down_revision: Union[str, Sequence[str], None] = '6e1de10f5901'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exchange_instruments', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('exchange_instruments', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('exchange_instruments', sa.Column('is_valid', sa.Boolean(), server_default=sa.text('1'), nullable=False))
    op.add_column('exchanges', sa.Column('is_active', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.drop_column('exchanges', 'status')
    op.add_column('instruments', sa.Column('is_active', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.drop_column('instruments', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instruments', sa.Column('status', mysql.ENUM('active', 'inactive', collation='utf8mb4_unicode_ci'), nullable=False))
    op.drop_column('instruments', 'is_active')
    op.add_column('exchanges', sa.Column('status', mysql.ENUM('active', 'inactive', collation='utf8mb4_unicode_ci'), nullable=False))
    op.drop_column('exchanges', 'is_active')
    op.drop_column('exchange_instruments', 'is_valid')
    op.drop_column('exchange_instruments', 'updated_at')
    op.drop_column('exchange_instruments', 'created_at')
    # ### end Alembic commands ###
