"""users, email_verifications, password_resets token_hash byte 타입으로 변경

Revision ID: 3df2f1520db5
Revises: 5de9c214c252
Create Date: 2025-11-13 21:53:14.307399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3df2f1520db5'
down_revision: Union[str, Sequence[str], None] = '5de9c214c252'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_verifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email_ciphertext', sa.LargeBinary(), nullable=False),
    sa.Column('email_fingerprint', sa.BINARY(length=32), nullable=False),
    sa.Column('email_nonce', sa.BINARY(length=12), nullable=False),
    sa.Column('email_key_version', sa.SMALLINT(), nullable=False),
    sa.Column('token_hash', sa.BINARY(length=32), nullable=False),
    sa.Column('status', sa.Enum('pending', 'sent','consumed', 'cancelled', name='emailverificationstatus', create_constraint=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fail_count', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_fingerprint')
    )
    op.create_unique_constraint(None, 'sessions', ['token_hash'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sessions', type_='unique')
    op.drop_table('email_verifications')
    # ### end Alembic commands ###
