"""users 테이블 변경(is_service, is_marketing, is_privacy 추가)

Revision ID: 435d85ef22cc
Revises: d7ed04ae0055
Create Date: 2026-02-15 17:58:16.209831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '435d85ef22cc'
down_revision: Union[str, Sequence[str], None] = 'd7ed04ae0055'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_service', sa.Boolean(), server_default=sa.text('0'), nullable=False))
    op.add_column('users', sa.Column('is_privacy', sa.Boolean(), server_default=sa.text('0'), nullable=False))
    op.add_column('users', sa.Column('is_marketing', sa.Boolean(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_marketing')
    op.drop_column('users', 'is_privacy')
    op.drop_column('users', 'is_service')
    # ### end Alembic commands ###
