"""create backfill_requests, backfill_request_items table

Revision ID: 444232d76058
Revises: 9a08912d9344
Create Date: 2026-05-22 15:40:50.517225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '444232d76058'
down_revision: Union[str, Sequence[str], None] = '9a08912d9344'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backfill_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_backfill_requests_created', 'backfill_requests', ['created_at'], unique=False)
    op.create_index(op.f('ix_backfill_requests_user_id'), 'backfill_requests', ['user_id'], unique=False)
    op.create_table('backfill_request_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('backfill_request_id', sa.Integer(), nullable=False),
    sa.Column('exchange_instrument_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'retry_wait', 'completed', 'failed', 'cancelled', name='backfill_request_item_status', create_constraint=True), server_default='queued', nullable=False),
    sa.Column('cursor_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result_code', sa.String(length=64), nullable=True),
    sa.Column('result_message', sa.Text(), nullable=True),
    sa.Column('result_payload', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['backfill_request_id'], ['backfill_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['exchange_instrument_id'], ['exchange_instruments.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('backfill_request_id', 'exchange_instrument_id', name='uq_backfill_request_item')
    )
    op.create_index(op.f('ix_backfill_request_items_backfill_request_id'), 'backfill_request_items', ['backfill_request_id'], unique=False)
    op.create_index(op.f('ix_backfill_request_items_exchange_instrument_id'), 'backfill_request_items', ['exchange_instrument_id'], unique=False)
    op.create_index('ix_backfill_request_items_request_status', 'backfill_request_items', ['backfill_request_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_backfill_request_items_request_status', table_name='backfill_request_items')
    op.drop_index(op.f('ix_backfill_request_items_exchange_instrument_id'), table_name='backfill_request_items')
    op.drop_index(op.f('ix_backfill_request_items_backfill_request_id'), table_name='backfill_request_items')
    op.drop_table('backfill_request_items')
    op.drop_index(op.f('ix_backfill_requests_user_id'), table_name='backfill_requests')
    op.drop_index('ix_backfill_requests_created', table_name='backfill_requests')
    op.drop_table('backfill_requests')
    # ### end Alembic commands ###
