"""watchlist_items 인덱스 추가 및 테이블 속성 제거 (deleted_at)

Revision ID: 4c1a871d383f
Revises: 7abc350e0387
Create Date: 2026-03-13 22:15:51.583708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4c1a871d383f'
down_revision: Union[str, Sequence[str], None] = '7abc350e0387'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_wi_user_exchange_instrument', 'watchlist_items', ['user_id', 'exchange_instrument_id'], unique=False)
    op.drop_column('watchlist_items', 'deleted_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('watchlist_items', sa.Column('deleted_at', mysql.DATETIME(), nullable=True))
    op.drop_index('ix_wi_user_exchange_instrument', table_name='watchlist_items')
    # ### end Alembic commands ###
