"""add open_price_24h column to exchange_instrument_tickers

Revision ID: 4d3640282926
Revises: e8badc44a9ae
Create Date: 2026-03-26 16:28:24.506443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4d3640282926'
down_revision: Union[str, Sequence[str], None] = 'e8badc44a9ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exchange_instrument_tickers', sa.Column('open_price', sa.DECIMAL(precision=32, scale=16), nullable=False))
    op.add_column('exchange_instrument_tickers', sa.Column('close_price', sa.DECIMAL(precision=32, scale=16), nullable=False))
    op.drop_column('exchange_instrument_tickers', 'last_price')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exchange_instrument_tickers', sa.Column('last_price', mysql.DECIMAL(precision=32, scale=16), nullable=False))
    op.drop_column('exchange_instrument_tickers', 'close_price')
    op.drop_column('exchange_instrument_tickers', 'open_price')
    # ### end Alembic commands ###
