"""add normalized_price, normalized_volume column to exchange_instrument_tickers

Revision ID: 4ea2fb6d1797
Revises: 4d3640282926
Create Date: 2026-03-27 17:25:07.372276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ea2fb6d1797'
down_revision: Union[str, Sequence[str], None] = '4d3640282926'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exchange_instrument_tickers', sa.Column('normalized_price', sa.DECIMAL(precision=32, scale=16), nullable=False))
    op.add_column('exchange_instrument_tickers', sa.Column('normalized_volume', sa.DECIMAL(precision=32, scale=16), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exchange_instrument_tickers', 'normalized_volume')
    op.drop_column('exchange_instrument_tickers', 'normalized_price')
    # ### end Alembic commands ###
