"""outboxs.dedupe_key 칼럼 outbox_fingerprint으로 명칭 및 타입 수정

Revision ID: 55f6f80c522a
Revises: 7fabf7508434
Create Date: 2025-11-17 14:41:47.540025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '55f6f80c522a'
down_revision: Union[str, Sequence[str], None] = '7fabf7508434'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outboxs', sa.Column('outbox_fingerprint', sa.BINARY(length=32), nullable=True))
    op.drop_index(op.f('dedupe_key'), table_name='outboxs')
    op.create_unique_constraint(None, 'outboxs', ['outbox_fingerprint'])
    op.drop_column('outboxs', 'dedupe_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outboxs', sa.Column('dedupe_key', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=256), nullable=True))
    op.drop_constraint(None, 'outboxs', type_='unique')
    op.create_index(op.f('dedupe_key'), 'outboxs', ['dedupe_key'], unique=True)
    op.drop_column('outboxs', 'outbox_fingerprint')
    # ### end Alembic commands ###
