"""update rss news schema

Revision ID: 5efae499d9c2
Revises: b22763e5f22d
Create Date: 2026-05-19 00:04:56.691738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5efae499d9c2'
down_revision: Union[str, Sequence[str], None] = 'b22763e5f22d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. 새 컬럼 추가
    op.add_column('news_items', sa.Column('rss_source_id', sa.Integer(), nullable=False))

    # 2. 기존 FK 먼저 제거
    op.drop_constraint(op.f('news_items_ibfk_1'), 'news_items', type_='foreignkey')

    # 3. 기존 인덱스 제거
    op.drop_index(op.f('ix_news_item_source'), table_name='news_items')
    op.drop_index(op.f('ix_news_item_source_guid'), table_name='news_items')
    op.drop_index(op.f('ix_news_item_source_link_hash'), table_name='news_items')
    op.drop_index(op.f('ix_news_item_source_title_hash'), table_name='news_items')

    # 4. 새 인덱스 생성
    op.create_index('ix_news_item_source', 'news_items', ['rss_source_id'], unique=False)
    op.create_index('ix_news_item_source_guid', 'news_items', ['rss_source_id', 'guid'], unique=True)
    op.create_index('ix_news_item_source_link_hash', 'news_items', ['rss_source_id', 'link_hash'], unique=True)
    op.create_index('ix_news_item_source_title_hash', 'news_items', ['rss_source_id', 'title_hash'], unique=False)

    # 5. 새 FK 생성
    op.create_foreign_key(None, 'news_items', 'rss_sources', ['rss_source_id'], ['id'])

    # 6. 기존 컬럼 제거
    op.drop_column('news_items', 'source_id')

    # 1. 새 컬럼 추가
    op.add_column('rss_sources', sa.Column('rss_provider_id', sa.Integer(), nullable=False))

    # 2. 기존 FK 먼저 제거
    op.drop_constraint(op.f('rss_sources_ibfk_1'), 'rss_sources', type_='foreignkey')

    # 3. 기존 인덱스 제거
    op.drop_index(op.f('ix_rss_source_provider'), table_name='rss_sources')
    op.drop_index(op.f('ix_rss_source_provider_code'), table_name='rss_sources')

    # 4. 새 인덱스 생성
    op.create_index('ix_rss_source_provider', 'rss_sources', ['rss_provider_id'], unique=False)
    op.create_index('ix_rss_source_provider_code', 'rss_sources', ['rss_provider_id', 'code'], unique=False)

    # 5. 새 FK 생성
    op.create_foreign_key(None, 'rss_sources', 'rss_providers', ['rss_provider_id'], ['id'])

    # 6. 기존 컬럼 제거
    op.drop_column('rss_sources', 'provider_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # -------------------------
    # rss_sources: rss_provider_id -> provider_id
    # -------------------------
    op.add_column(
        "rss_sources",
        sa.Column("provider_id", mysql.INTEGER(), nullable=True),
    )

    op.execute("""
        UPDATE rss_sources
        SET provider_id = rss_provider_id
    """)

    # 기존 새 FK 먼저 제거
    op.drop_constraint(op.f("rss_sources_ibfk_1"), "rss_sources", type_="foreignkey")

    # 새 인덱스 제거
    op.drop_index("ix_rss_source_provider_code", table_name="rss_sources")
    op.drop_index("ix_rss_source_provider", table_name="rss_sources")

    # provider_id NOT NULL
    op.alter_column(
        "rss_sources",
        "provider_id",
        existing_type=mysql.INTEGER(),
        nullable=False,
    )

    # 기존 이름 인덱스/FK 복구
    op.create_index(
        op.f("ix_rss_source_provider"),
        "rss_sources",
        ["provider_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_rss_source_provider_code"),
        "rss_sources",
        ["provider_id", "code"],
        unique=False,
    )
    op.create_foreign_key(
        op.f("rss_sources_ibfk_1"),
        "rss_sources",
        "rss_providers",
        ["provider_id"],
        ["id"],
    )

    op.drop_column("rss_sources", "rss_provider_id")

    # -------------------------
    # news_items: rss_source_id -> source_id
    # -------------------------
    op.add_column(
        "news_items",
        sa.Column("source_id", mysql.INTEGER(), nullable=True),
    )

    op.execute("""
        UPDATE news_items
        SET source_id = rss_source_id
    """)

    # 기존 새 FK 먼저 제거
    op.drop_constraint(op.f("news_items_ibfk_1"), "news_items", type_="foreignkey")

    # 새 인덱스 제거
    op.drop_index("ix_news_item_source_title_hash", table_name="news_items")
    op.drop_index("ix_news_item_source_link_hash", table_name="news_items")
    op.drop_index("ix_news_item_source_guid", table_name="news_items")
    op.drop_index("ix_news_item_source", table_name="news_items")

    # source_id NOT NULL
    op.alter_column(
        "news_items",
        "source_id",
        existing_type=mysql.INTEGER(),
        nullable=False,
    )

    # 기존 이름 인덱스/FK 복구
    op.create_index(
        op.f("ix_news_item_source"),
        "news_items",
        ["source_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_news_item_source_guid"),
        "news_items",
        ["source_id", "guid"],
        unique=True,
    )
    op.create_index(
        op.f("ix_news_item_source_link_hash"),
        "news_items",
        ["source_id", "link_hash"],
        unique=True,
    )
    op.create_index(
        op.f("ix_news_item_source_title_hash"),
        "news_items",
        ["source_id", "title_hash"],
        unique=False,
    )
    op.create_foreign_key(
        op.f("news_items_ibfk_1"),
        "news_items",
        "rss_sources",
        ["source_id"],
        ["id"],
    )

    op.drop_column("news_items", "rss_source_id")
