"""add channel_providers table and user_channels.provider_id FK

Revision ID: 61e604a7bf19
Revises: 823a34a405f1
Create Date: 2025-10-02 14:51:00.182114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '61e604a7bf19'
down_revision: Union[str, Sequence[str], None] = '823a34a405f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel_providers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('user_schema', sa.JSON(), nullable=True),
    sa.Column('admin_schema', sa.JSON(), nullable=True),
    sa.Column('rate_limit_policy', sa.JSON(), nullable=True),
    sa.Column('retry_policy', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index('ix_channel_providers_active', 'channel_providers', ['is_active'], unique=False)
    op.add_column('user_channels', sa.Column('channel_provider_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_user_channels_type'), table_name='user_channels')
    op.create_index(op.f('ix_user_channels_channel_provider_id'), 'user_channels', ['channel_provider_id'], unique=False)
    op.create_foreign_key(None, 'user_channels', 'channel_providers', ['channel_provider_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('user_channels', 'channel_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_channels', sa.Column('channel_type', mysql.ENUM('email', 'webhook', 'telegram', 'slack', collation='utf8mb4_unicode_ci'), nullable=False))
    op.drop_constraint(None, 'user_channels', type_='foreignkey')
    op.drop_index(op.f('ix_user_channels_channel_provider_id'), table_name='user_channels')
    op.create_index(op.f('ix_user_channels_type'), 'user_channels', ['channel_type'], unique=False)
    op.drop_column('user_channels', 'channel_provider_id')
    op.drop_index('ix_channel_providers_active', table_name='channel_providers')
    op.drop_table('channel_providers')
    # ### end Alembic commands ###
