"""password_resets에 sent_at 추가 및 used_at → consumed_at 변경

Revision ID: 6ab84b8dcaaf
Revises: 435d85ef22cc
Create Date: 2026-02-23 23:13:51.889018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6ab84b8dcaaf'
down_revision: Union[str, Sequence[str], None] = '435d85ef22cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('password_resets', sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('password_resets', sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('password_resets', 'used_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('password_resets', sa.Column('used_at', mysql.DATETIME(), nullable=True))
    op.drop_column('password_resets', 'consumed_at')
    op.drop_column('password_resets', 'sent_at')
    # ### end Alembic commands ###
