"""add price_snapshots_1h, price_snapshots_1d table
modify price_snapshots_1m, exchange_instruments table
rename column active to is_active 
rename column bucket_minute to ts_open
add column updated_at
drop prices_latest table

Revision ID: 6e1de10f5901
Revises: ecc45068254e
Create Date: 2025-09-25 18:02:01.865403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e1de10f5901'
down_revision: Union[str, Sequence[str], None] = 'ecc45068254e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_price_1m_instrument_id'), table_name='price_snapshots_1m')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_price_1m_instrument_id'), 'price_snapshots_1m', ['instrument_id'], unique=False)
    # ### end Alembic commands ###
