"""outboxs aggregate_type null 비허용, exchange_instruments price_precision, qty_precision null 허용

Revision ID: 6ec582a52d70
Revises: c770a18b5e3a
Create Date: 2026-01-13 18:44:57.714520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6ec582a52d70'
down_revision: Union[str, Sequence[str], None] = 'c770a18b5e3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exchange_instruments', 'price_precision',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('exchange_instruments', 'qty_precision',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('outboxs', 'aggregate_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('outboxs', 'aggregate_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               nullable=True)
    op.alter_column('exchange_instruments', 'qty_precision',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('exchange_instruments', 'price_precision',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
