"""add table outbox_attempts, alert table outboxs

Revision ID: 6ef315795444
Revises: 8c187216c158
Create Date: 2025-10-20 15:34:32.414616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6ef315795444'
down_revision: Union[str, Sequence[str], None] = '8c187216c158'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outboxs', sa.Column('trace_id', sa.String(length=36), nullable=False))
    op.add_column('outboxs', sa.Column('aggregate_type', sa.String(length=50), nullable=True))
    op.add_column('outboxs', sa.Column('dedupe_key', sa.String(length=256), nullable=True))
    op.add_column('outboxs', sa.Column('last_attempted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('outboxs', sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('outboxs', sa.Column('final_failed_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index('ix_outbox_agg', 'outboxs', ['aggregate_type', 'aggregate_id'], unique=False)
    op.create_index('ix_outbox_status_next', 'outboxs', ['status', 'next_run_at'], unique=False)
    op.create_unique_constraint(None, 'outboxs', ['dedupe_key'])
    op.drop_column('outboxs', 'payload')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outboxs', sa.Column('payload', mysql.JSON(), nullable=False))
    op.drop_constraint(None, 'outboxs', type_='unique')
    op.drop_index('ix_outbox_status_next', table_name='outboxs')
    op.drop_index('ix_outbox_agg', table_name='outboxs')
    op.drop_column('outboxs', 'final_failed_at')
    op.drop_column('outboxs', 'sent_at')
    op.drop_column('outboxs', 'last_attempted_at')
    op.drop_column('outboxs', 'dedupe_key')
    op.drop_column('outboxs', 'aggregate_type')
    op.drop_column('outboxs', 'trace_id')
    # ### end Alembic commands ###
