"""instruments 테이블 속성 추가 (name)

Revision ID: 7abc350e0387
Revises: 013279996319
Create Date: 2026-03-13 19:50:38.773363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7abc350e0387'
down_revision: Union[str, Sequence[str], None] = '013279996319'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "instruments",
        sa.Column("name", sa.String(length=64), nullable=True)
    )

    op.execute("""
    UPDATE instruments
    SET name = symbol
    WHERE name IS NULL
    """)

    op.alter_column(
        "instruments",
        "name",
        existing_type=sa.String(length=64),
        nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instruments', 'name')
    # ### end Alembic commands ###
