"""add, modify column (is_valid, update_at, sort_order, is_default) default and server_default 

Revision ID: 7f9af87fd032
Revises: eec5d47a8473
Create Date: 2025-09-22 15:02:57.345339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f9af87fd032'
down_revision: Union[str, Sequence[str], None] = 'eec5d47a8473'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exchanges', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('instruments', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('user_channels', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('watchlist_items', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('watchlist_items', 'updated_at')
    op.drop_column('users', 'updated_at')
    op.drop_column('user_channels', 'updated_at')
    op.drop_column('instruments', 'updated_at')
    op.drop_column('exchanges', 'updated_at')
    # ### end Alembic commands ###
