"""user_channels.config_fingerprint 자료형 변경

Revision ID: 7fabf7508434
Revises: 3df2f1520db5
Create Date: 2025-11-15 15:44:23.164350

"""
from typing import Sequence, Union

from alembic import op, context
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7fabf7508434'
down_revision: Union[str, Sequence[str], None] = '3df2f1520db5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('user_channels', 'config_fingerprint',
    #            existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64),
    #            type_=sa.BINARY(length=32),
    #            existing_nullable=True)

    op.add_column(
        "user_channels",
        sa.Column("config_fingerprint_tmp", sa.BINARY(32), nullable=True),
    )

    # 2) 기존 hex 문자열(길이 64, 0-9A-Fa-f) → bytes 로 변환해서 temp 컬럼에 저장
    op.execute(
        """
        UPDATE user_channels
        SET config_fingerprint_tmp = UNHEX(config_fingerprint)
        WHERE config_fingerprint IS NOT NULL
          AND LENGTH(config_fingerprint) = 64
          AND config_fingerprint REGEXP '^[0-9A-Fa-f]+$';
        """
    )

    # 3) 변환 안 된(=비정상 데이터) row가 있는지 체크
    if not context.is_offline_mode():
        bind = op.get_bind()
        bad_count = bind.execute(
            sa.text(
                """
                SELECT COUNT(*) AS c
                FROM user_channels
                WHERE config_fingerprint IS NOT NULL
                AND config_fingerprint_tmp IS NULL;
                """
            )
        ).scalar()

        if bad_count:
            # 실데이터 있는 환경에서 이상 데이터 있으면 바로 중단
            raise Exception(
                f"user_channels.config_fingerprint 에서 {bad_count}개 row 변환 실패 "
                "(길이 64 hex 문자열이 아님)"
            )

    # 4) 원래 컬럼 삭제
    op.drop_column("user_channels", "config_fingerprint")

    # 5) temp 컬럼을 최종 이름으로 변경
    op.alter_column(
        "user_channels",
        "config_fingerprint_tmp",
        new_column_name="config_fingerprint",
        existing_type=sa.BINARY(32),
        nullable=True,
    )

    op.create_index(
        "ix_user_channels_config_fingerprint",
        "user_channels",
        ["config_fingerprint"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 1) hex 문자열용 임시 컬럼 추가
    op.add_column(
        "user_channels",
        sa.Column(
            "config_fingerprint_str",
            mysql.VARCHAR(length=64, collation="utf8mb4_unicode_ci"),
            nullable=True,
        ),
    )

    # 2) bytes → hex 문자열(길이 64)로 변환
    op.execute(
        """
        UPDATE user_channels
        SET config_fingerprint_str = HEX(config_fingerprint)
        WHERE config_fingerprint IS NOT NULL;
        """
    )

    # 3) BINARY 컬럼 삭제
    op.drop_column("user_channels", "config_fingerprint")

    # 4) 임시 문자열 컬럼을 원래 이름으로 변경
    op.alter_column(
        "user_channels",
        "config_fingerprint_str",
        new_column_name="config_fingerprint",
        existing_type=mysql.VARCHAR(length=64, collation="utf8mb4_unicode_ci"),
        nullable=True,
    )

    # 5) 다시 인덱스 생성
    op.create_index(
        "ix_user_channels_config_fingerprint",
        "user_channels",
        ["config_fingerprint"],
    )
    # ### end Alembic commands ###
