"""add table outbox_attempts, alert table outboxs

Revision ID: 8c187216c158
Revises: dca0cdcbc567
Create Date: 2025-10-20 15:32:08.184098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c187216c158'
down_revision: Union[str, Sequence[str], None] = 'dca0cdcbc567'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
