"""oauth_providers 칼럼명 수정 enabled -> is_active

Revision ID: 8e58b1e22c7f
Revises: 6ab84b8dcaaf
Create Date: 2026-03-02 13:45:40.049662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8e58b1e22c7f'
down_revision: Union[str, Sequence[str], None] = '6ab84b8dcaaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oauth_providers', sa.Column('is_active', sa.Boolean(), server_default=sa.text('0'), nullable=False))
    op.drop_column('oauth_providers', 'enabled')
    op.alter_column('password_resets', 'consumed_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='토큰 사용 시각',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('password_resets', 'consumed_at',
               existing_type=mysql.DATETIME(),
               comment='토큰 사용 시각',
               existing_nullable=True)
    op.add_column('oauth_providers', sa.Column('enabled', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.drop_column('oauth_providers', 'is_active')
    # ### end Alembic commands ###
