"""exchanges, instruments add column name_ko

Revision ID: 9a08912d9344
Revises: b379ae5ae5d9
Create Date: 2026-06-09 17:29:18.677235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a08912d9344'
down_revision: Union[str, Sequence[str], None] = 'b379ae5ae5d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exchanges', sa.Column('name_ko', sa.String(length=100), nullable=True))
    op.add_column('instruments', sa.Column('name_ko', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instruments', 'name_ko')
    op.drop_column('exchanges', 'name_ko')
    # ### end Alembic commands ###
