"""schema: AssetType에 'fiat' 추가 및 KRW 데이터 업데이트

Revision ID: 9a63b0cc60f7
Revises: 457634e9ee76
Create Date: 2025-09-26 19:04:43.202597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a63b0cc60f7'
down_revision: Union[str, Sequence[str], None] = '457634e9ee76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
