"""add is_quiet_hours column to users

Revision ID: 9fffc028c249
Revises: 2759784518f4
Create Date: 2026-04-11 19:00:30.781252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fffc028c249'
down_revision: Union[str, Sequence[str], None] = '2759784518f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_quiet_hours', sa.Boolean(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_quiet_hours')
    # ### end Alembic commands ###
