"""rename table deliveries, alert_deliveries

Revision ID: a3d6e20ff230
Revises: ab6cefb8dae8
Create Date: 2026-05-13 15:01:17.707807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a3d6e20ff230'
down_revision: Union[str, Sequence[str], None] = 'ab6cefb8dae8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_deliveries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('alert_event_id', sa.Integer(), nullable=False),
    sa.Column('user_channel_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'SENT', 'FAILED', name='alertdeliverystatus', create_constraint=True), server_default='queued', nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('response_code', sa.Integer(), nullable=True),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['alert_event_id'], ['alert_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_channel_id'], ['user_channels.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_deliveries_alert_event_id'), 'alert_deliveries', ['alert_event_id'], unique=False)
    op.create_index(op.f('ix_alert_deliveries_user_channel_id'), 'alert_deliveries', ['user_channel_id'], unique=False)
    op.create_index('ix_deliveries_status', 'alert_deliveries', ['status'], unique=False)

    op.drop_table('deliveries')
    
    op.add_column(
        'alert_events',
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True)
    )

    op.execute("""
        UPDATE alert_events
        SET updated_at = COALESCE(created_at, NOW())
        WHERE updated_at IS NULL
    """)

    op.alter_column(
        'alert_events',
        'updated_at',
        existing_type=sa.DateTime(timezone=True),
        nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alert_events', 'updated_at')
    op.create_table('deliveries',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('alert_event_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_channel_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', mysql.ENUM('queued', 'sent', 'failed'), nullable=False),
    sa.Column('sent_at', mysql.DATETIME(), nullable=True),
    sa.Column('response_code', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('response_body', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False),
    sa.ForeignKeyConstraint(['alert_event_id'], ['alert_events.id'], name=op.f('deliveries_ibfk_1'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_channel_id'], ['user_channels.id'], name=op.f('deliveries_ibfk_2'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_deliveries_user_channel_id'), 'deliveries', ['user_channel_id'], unique=False)
    op.create_index(op.f('ix_deliveries_status'), 'deliveries', ['status'], unique=False)
    op.create_index(op.f('ix_deliveries_alert_event_id'), 'deliveries', ['alert_event_id'], unique=False)

    op.drop_table('alert_deliveries')
    # ### end Alembic commands ###
