"""alter backfill_requests table add column(base)

Revision ID: a5bd60064bfd
Revises: 444232d76058
Create Date: 2026-05-22 17:37:24.174563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5bd60064bfd'
down_revision: Union[str, Sequence[str], None] = '444232d76058'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backfill_requests', sa.Column('base', sa.Enum('1m', '1h', '1d', name='backfill_request_base', create_constraint=True), server_default='1m', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('backfill_requests', 'base')
    # ### end Alembic commands ###
