"""alert event table add column status, queued_at

Revision ID: ab6cefb8dae8
Revises: 1d5869f297ff
Create Date: 2026-05-11 00:14:09.801590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab6cefb8dae8'
down_revision: Union[str, Sequence[str], None] = '1d5869f297ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alert_events', sa.Column('status', sa.Enum('pending', 'queued', 'dispatched', 'skipped', name='alerteventstatus', create_constraint=True), server_default='pending', nullable=False))
    op.add_column('alert_events', sa.Column('queued_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index('ix_alert_events_status_detected', 'alert_events', ['status', 'detected_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_alert_events_status_detected', table_name='alert_events')
    op.drop_column('alert_events', 'queued_at')
    op.drop_column('alert_events', 'status')
    # ### end Alembic commands ###
