"""create news domain tables (rss_providers, rss_sources, news_item_stats, news_items, news_item_translations)

Revision ID: b22763e5f22d
Revises: c5645280b561
Create Date: 2026-05-17 18:17:05.308695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b22763e5f22d'
down_revision: Union[str, Sequence[str], None] = 'c5645280b561'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rss_providers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('homepage_url', sa.String(length=500), nullable=True),
    sa.Column('language', sa.Enum('ko', 'en', 'ja', 'zh', 'unknown', name='languagecode', create_constraint=True), server_default='en', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('request_timeout_sec', sa.Integer(), server_default=sa.text('10'), nullable=False),
    sa.Column('rate_limit_policy', sa.JSON(), nullable=True),
    sa.Column('retry_policy', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index('ix_rss_provider_active', 'rss_providers', ['is_active'], unique=False)
    op.create_table('rss_sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('feed_url', sa.String(length=500), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('etag', sa.String(length=255), nullable=True),
    sa.Column('last_modified', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['rss_providers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index('ix_rss_source_active', 'rss_sources', ['is_active'], unique=False)
    op.create_index('ix_rss_source_provider', 'rss_sources', ['provider_id'], unique=False)
    op.create_index('ix_rss_source_provider_code', 'rss_sources', ['provider_id', 'code'], unique=False)
    op.create_table('news_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('guid', sa.String(length=500), nullable=True),
    sa.Column('link', sa.String(length=1000), nullable=False),
    sa.Column('canonical_link', sa.String(length=1000), nullable=True),
    sa.Column('title_original', sa.String(length=500), nullable=False),
    sa.Column('description_original', sa.Text(), nullable=True),
    sa.Column('content_original', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=1000), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('language', sa.Enum('ko', 'en', 'ja', 'zh', 'unknown', name='languagecode', create_constraint=True), server_default='unknown', nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('title_hash', sa.String(length=64), nullable=False),
    sa.Column('link_hash', sa.String(length=64), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('active', 'hidden', 'deleted', name='newsitemstatus', create_constraint=True), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['rss_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_news_item_published', 'news_items', ['published_at'], unique=False)
    op.create_index('ix_news_item_source', 'news_items', ['source_id'], unique=False)
    op.create_index('ix_news_item_source_guid', 'news_items', ['source_id', 'guid'], unique=True)
    op.create_index('ix_news_item_source_link_hash', 'news_items', ['source_id', 'link_hash'], unique=True)
    op.create_index('ix_news_item_source_title_hash', 'news_items', ['source_id', 'title_hash'], unique=False)
    op.create_index('ix_news_item_status_published', 'news_items', ['status', 'published_at'], unique=False)
    op.create_table('news_item_stats',
    sa.Column('news_item_id', sa.Integer(), nullable=False),
    sa.Column('click_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('share_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_clicked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['news_item_id'], ['news_items.id'], ),
    sa.PrimaryKeyConstraint('news_item_id')
    )
    op.create_table('news_item_translations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('news_item_id', sa.Integer(), nullable=False),
    sa.Column('locale', sa.Enum('ko', 'en', 'ja', 'zh', 'unknown', name='languagecode', create_constraint=True), server_default='ko', nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('pending', 'processing', 'done', 'failed', 'skipped', name='newsitemtranslationstatus', create_constraint=True), server_default='pending', nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('translated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['news_item_id'], ['news_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_news_item_translation_item_locale', 'news_item_translations', ['news_item_id', 'locale'], unique=True)
    op.create_index('ix_news_item_translation_status_locale', 'news_item_translations', ['status', 'locale'], unique=False)
    op.alter_column('user_channels', 'address',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_channels', 'address',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               nullable=True)
    op.drop_index('ix_news_item_translation_status_locale', table_name='news_item_translations')
    op.drop_index('ix_news_item_translation_item_locale', table_name='news_item_translations')
    op.drop_table('news_item_translations')
    op.drop_table('news_item_stats')
    op.drop_index('ix_news_item_status_published', table_name='news_items')
    op.drop_index('ix_news_item_source_title_hash', table_name='news_items')
    op.drop_index('ix_news_item_source_link_hash', table_name='news_items')
    op.drop_index('ix_news_item_source_guid', table_name='news_items')
    op.drop_index('ix_news_item_source', table_name='news_items')
    op.drop_index('ix_news_item_published', table_name='news_items')
    op.drop_table('news_items')
    op.drop_index('ix_rss_source_provider_code', table_name='rss_sources')
    op.drop_index('ix_rss_source_provider', table_name='rss_sources')
    op.drop_index('ix_rss_source_active', table_name='rss_sources')
    op.drop_table('rss_sources')
    op.drop_index('ix_rss_provider_active', table_name='rss_providers')
    op.drop_table('rss_providers')
    # ### end Alembic commands ###
