"""update news_item_translations provider

Revision ID: b379ae5ae5d9
Revises: 346444b603f1
Create Date: 2026-05-21 01:16:30.032153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b379ae5ae5d9'
down_revision: Union[str, Sequence[str], None] = '346444b603f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('news_item_translations', 'provider',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               type_=sa.Enum('GOOGLE', name='translationcode', create_constraint=True),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('news_item_translations', 'provider',
               existing_type=sa.Enum('GOOGLE', name='translationcode', create_constraint=True),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               existing_nullable=True)
    # ### end Alembic commands ###
