"""update user_channels schema

Revision ID: b412adcdc797
Revises: e61a4a39387a
Create Date: 2026-04-17 21:35:50.271743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b412adcdc797'
down_revision: Union[str, Sequence[str], None] = 'e61a4a39387a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_channels', sa.Column('config_hash', sa.BINARY(length=32), nullable=True))
    op.drop_index(op.f('ix_user_channels_config_fingerprint'), table_name='user_channels')
    op.create_index(op.f('ix_user_channels_config_hash'), 'user_channels', ['config_hash'], unique=False)
    op.drop_column('user_channels', 'config_fingerprint')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_channels', sa.Column('config_fingerprint', sa.BINARY(length=32), nullable=True))
    op.drop_index(op.f('ix_user_channels_config_hash'), table_name='user_channels')
    op.create_index(op.f('ix_user_channels_config_fingerprint'), 'user_channels', ['config_fingerprint'], unique=False)
    op.drop_column('user_channels', 'config_hash')
    # ### end Alembic commands ###
