"""schema: alerts 테이블을 exchange_instrument_id 단일 FK 기반으로 전환

Revision ID: ba15068e02c6
Revises: 59213d179cfe
Create Date: 2025-09-25 20:45:31.297647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ba15068e02c6'
down_revision: Union[str, Sequence[str], None] = '59213d179cfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('exchange_instrument_id', sa.Integer(), nullable=True))
    # op.drop_index(op.f('ix_alerts_exchange_id'), table_name='alerts')
    # op.drop_index(op.f('ix_alerts_instrument_id'), table_name='alerts')
    op.create_index(op.f('ix_alerts_exchange_instrument_id'), 'alerts', ['exchange_instrument_id'], unique=False)
    op.drop_constraint(op.f('alerts_ibfk_2'), 'alerts', type_='foreignkey')
    op.drop_constraint(op.f('alerts_ibfk_3'), 'alerts', type_='foreignkey')
    op.create_foreign_key(None, 'alerts', 'exchange_instruments', ['exchange_instrument_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('alerts', 'exchange_id')
    op.drop_column('alerts', 'instrument_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('instrument_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('alerts', sa.Column('exchange_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'alerts', type_='foreignkey')
    op.create_foreign_key(op.f('alerts_ibfk_3'), 'alerts', 'instruments', ['instrument_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('alerts_ibfk_2'), 'alerts', 'exchanges', ['exchange_id'], ['id'], ondelete='RESTRICT')
    op.drop_index(op.f('ix_alerts_exchange_instrument_id'), table_name='alerts')
    op.create_index(op.f('ix_alerts_instrument_id'), 'alerts', ['instrument_id'], unique=False)
    op.create_index(op.f('ix_alerts_exchange_id'), 'alerts', ['exchange_id'], unique=False)
    op.drop_column('alerts', 'exchange_instrument_id')
    # ### end Alembic commands ###
