"""move alert scope to alert types, craete table alert_bucket_policies

Revision ID: c3f740afa293
Revises: f5737b7490c3
Create Date: 2026-05-05 20:41:23.098968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c3f740afa293'
down_revision: Union[str, Sequence[str], None] = 'f5737b7490c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_bucket_policies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('alert_type_id', sa.Integer(), nullable=False),
    sa.Column('exchange_instrument_id', sa.Integer(), nullable=True),
    sa.Column('bucket_size', sa.DECIMAL(precision=20, scale=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['alert_type_id'], ['alert_types.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['exchange_instrument_id'], ['exchange_instruments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exchange_instrument_id', 'alert_type_id', name='uq_alert_bucket_policy_scope')
    )
    op.create_index(op.f('ix_alert_bucket_policies_alert_type_id'), 'alert_bucket_policies', ['alert_type_id'], unique=False)
    op.create_index(op.f('ix_alert_bucket_policies_exchange_instrument_id'), 'alert_bucket_policies', ['exchange_instrument_id'], unique=False)
    op.add_column('alert_types', sa.Column('scope', sa.Enum('single', 'cross', name='alertscope', create_constraint=True), server_default='single', nullable=False))
    op.drop_column('alerts', 'scope')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('scope', mysql.ENUM('single', 'cross', collation='utf8mb4_unicode_ci'), nullable=False))
    op.drop_column('alert_types', 'scope')
    op.drop_index(op.f('ix_alert_bucket_policies_exchange_instrument_id'), table_name='alert_bucket_policies')
    op.drop_index(op.f('ix_alert_bucket_policies_alert_type_id'), table_name='alert_bucket_policies')
    op.drop_table('alert_bucket_policies')
    # ### end Alembic commands ###
