"""alert_deliveries table add column updated_at

Revision ID: c5645280b561
Revises: 31c8b45c0a02
Create Date: 2026-05-13 19:15:28.416164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5645280b561'
down_revision: Union[str, Sequence[str], None] = '31c8b45c0a02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alert_deliveries', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alert_deliveries', 'updated_at')
    # ### end Alembic commands ###
