"""Drop unique constraint on email_verifications.email_fingerprint

Revision ID: c770a18b5e3a
Revises: f76aae632c99
Create Date: 2025-12-19 15:29:42.207789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c770a18b5e3a'
down_revision: Union[str, Sequence[str], None] = 'f76aae632c99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('email_fingerprint'), table_name='email_verifications')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('email_fingerprint'), 'email_verifications', ['email_fingerprint'], unique=True)
    # ### end Alembic commands ###
