"""rev_000X: schema sync with 20250918 DDL

Revision ID: ca47ead8f7a5
Revises: aa5166689525
Create Date: 2025-09-19 11:24:38.952563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ca47ead8f7a5'
down_revision: Union[str, Sequence[str], None] = 'aa5166689525'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchanges',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('base_url', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', name='exchangestatus', create_constraint=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('instruments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=64), nullable=False),
    sa.Column('base_asset', sa.String(length=32), nullable=False),
    sa.Column('quote_asset', sa.String(length=32), nullable=False),
    sa.Column('asset_type', sa.Enum('crypto', 'fx', 'stock', 'future', name='assettype', create_constraint=True), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', name='instrumentstatus', create_constraint=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol')
    )
    op.create_table('exchange_instruments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exchange_id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('exchange_symbol', sa.String(length=64), nullable=False),
    sa.Column('price_precision', sa.Integer(), nullable=False),
    sa.Column('qty_precision', sa.Integer(), nullable=False),
    sa.Column('min_notional', sa.DECIMAL(precision=20, scale=10), nullable=True),
    sa.Column('active', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exchange_id'], ['exchanges.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exchange_instruments_exchange_id'), 'exchange_instruments', ['exchange_id'], unique=False)
    op.create_index(op.f('ix_exchange_instruments_exchange_symbol'), 'exchange_instruments', ['exchange_symbol'], unique=False)
    op.create_index(op.f('ix_exchange_instruments_instrument_id'), 'exchange_instruments', ['instrument_id'], unique=False)
    op.create_table('password_resets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_password_resets_user_id'), 'password_resets', ['user_id'], unique=False)
    op.create_table('price_snapshots_1m',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exchange_id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('bucket_minute', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.DECIMAL(precision=32, scale=16), nullable=False),
    sa.Column('high', sa.DECIMAL(precision=32, scale=16), nullable=False),
    sa.Column('low', sa.DECIMAL(precision=32, scale=16), nullable=False),
    sa.Column('close', sa.DECIMAL(precision=32, scale=16), nullable=False),
    sa.Column('volume', sa.DECIMAL(precision=32, scale=16), nullable=False),
    sa.ForeignKeyConstraint(['exchange_id'], ['exchanges.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exchange_id', 'instrument_id', 'bucket_minute', name='uq_price_1m_key')
    )
    op.create_index('ix_price_1m_bucket', 'price_snapshots_1m', ['bucket_minute'], unique=False)
    op.create_index('ix_price_1m_instr_bucket', 'price_snapshots_1m', ['instrument_id', 'bucket_minute'], unique=False)
    op.create_table('prices_latest',
    sa.Column('exchange_id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('last_price', sa.DECIMAL(precision=32, scale=16), nullable=False),
    sa.Column('volume_24h', sa.DECIMAL(precision=32, scale=16), nullable=True),
    sa.Column('high_24h', sa.DECIMAL(precision=32, scale=16), nullable=True),
    sa.Column('low_24h', sa.DECIMAL(precision=32, scale=16), nullable=True),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['exchange_id'], ['exchanges.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('exchange_id', 'instrument_id', name='pk_prices_latest')
    )
    op.create_index('ix_prices_latest_instrument', 'prices_latest', ['instrument_id'], unique=False)
    op.create_index('ix_prices_latest_ts', 'prices_latest', ['ts'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('ip_addr', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('ix_sessions_expires', 'sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('user_channels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('channel_type', sa.Enum('email', 'webhook', 'telegram', 'slack', name='channeltype', create_constraint=True), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_channels_type', 'user_channels', ['channel_type'], unique=False)
    op.create_index(op.f('ix_user_channels_user_id'), 'user_channels', ['user_id'], unique=False)
    op.create_table('user_identities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider_type', sa.Enum('google', 'github', 'kakao', 'naver', name='providertype', create_constraint=True), nullable=False),
    sa.Column('provider_user_id', sa.String(length=128), nullable=False),
    sa.Column('access_token', sa.String(length=2048), nullable=True),
    sa.Column('refresh_token', sa.String(length=2048), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_type', 'provider_user_id', name='uq_identity_provider_uid')
    )
    op.create_index(op.f('ix_user_identities_user_id'), 'user_identities', ['user_id'], unique=False)
    op.create_table('watchlist_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('exchange_id', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exchange_id'], ['exchanges.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watchlist_items_exchange_id'), 'watchlist_items', ['exchange_id'], unique=False)
    op.create_index(op.f('ix_watchlist_items_instrument_id'), 'watchlist_items', ['instrument_id'], unique=False)
    op.create_index(op.f('ix_watchlist_items_user_id'), 'watchlist_items', ['user_id'], unique=False)
    op.create_table('alert_channel_targets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('user_channel_id', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_channel_id'], ['user_channels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alert_id', 'user_channel_id', name='uq_alert_channel_target')
    )
    op.create_index(op.f('ix_alert_channel_targets_alert_id'), 'alert_channel_targets', ['alert_id'], unique=False)
    op.create_index(op.f('ix_alert_channel_targets_user_channel_id'), 'alert_channel_targets', ['user_channel_id'], unique=False)
    op.create_table('alert_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('exchange_id', sa.Integer(), nullable=True),
    sa.Column('instrument_id', sa.Integer(), nullable=True),
    sa.Column('trigger_value', sa.DECIMAL(precision=32, scale=16), nullable=True),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('dedup_key', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['exchange_id'], ['exchanges.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedup_key')
    )
    op.create_index('ix_alert_events_alert_detected', 'alert_events', ['alert_id', 'detected_at'], unique=False)
    op.create_index(op.f('ix_alert_events_alert_id'), 'alert_events', ['alert_id'], unique=False)
    op.create_index(op.f('ix_alert_events_exchange_id'), 'alert_events', ['exchange_id'], unique=False)
    op.create_index(op.f('ix_alert_events_instrument_id'), 'alert_events', ['instrument_id'], unique=False)
    op.create_table('deliveries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('alert_event_id', sa.Integer(), nullable=False),
    sa.Column('user_channel_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'sent', 'failed', name='deliverystatus', create_constraint=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('response_code', sa.Integer(), nullable=True),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['alert_event_id'], ['alert_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_channel_id'], ['user_channels.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deliveries_alert_event_id'), 'deliveries', ['alert_event_id'], unique=False)
    op.create_index('ix_deliveries_status', 'deliveries', ['status'], unique=False)
    op.create_index(op.f('ix_deliveries_user_channel_id'), 'deliveries', ['user_channel_id'], unique=False)
    op.add_column('alerts', sa.Column('scope', sa.Enum('single', 'cross', name='alertscope', create_constraint=True), nullable=False))
    op.add_column('alerts', sa.Column('exchange_id', sa.Integer(), nullable=True))
    op.add_column('alerts', sa.Column('instrument_id', sa.Integer(), nullable=True))
    op.add_column('alerts', sa.Column('throttle_seconds', sa.Integer(), nullable=False))
    op.add_column('alerts', sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True))
    op.add_column('alerts', sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True))
    op.add_column('alerts', sa.Column('timezone', sa.String(length=64), nullable=False))
    op.add_column('alerts', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('alerts', 'params',
               existing_type=mysql.JSON(),
               nullable=False)
    op.drop_index(op.f('ix_alerts_id'), table_name='alerts')
    op.create_index(op.f('ix_alerts_exchange_id'), 'alerts', ['exchange_id'], unique=False)
    op.create_index(op.f('ix_alerts_instrument_id'), 'alerts', ['instrument_id'], unique=False)
    op.create_index('ix_alerts_status', 'alerts', ['status'], unique=False)
    op.create_index('ix_alerts_type', 'alerts', ['type'], unique=False)
    op.create_index(op.f('ix_alerts_user_id'), 'alerts', ['user_id'], unique=False)
    op.create_unique_constraint('uq_alerts_user_name', 'alerts', ['user_id', 'name'])
    op.create_foreign_key(None, 'alerts', 'exchanges', ['exchange_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'alerts', 'instruments', ['instrument_id'], ['id'], ondelete='RESTRICT')
    op.add_column('users', sa.Column('nickname', sa.String(length=100), nullable=False))
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=False))
    op.alter_column('users', 'last_login_at',
               existing_type=mysql.DATETIME())
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False))
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.alter_column('users', 'last_login_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'nickname')
    op.drop_constraint(None, 'alerts', type_='foreignkey')
    op.drop_constraint(None, 'alerts', type_='foreignkey')
    op.drop_constraint('uq_alerts_user_name', 'alerts', type_='unique')
    op.drop_index(op.f('ix_alerts_user_id'), table_name='alerts')
    op.drop_index('ix_alerts_type', table_name='alerts')
    op.drop_index('ix_alerts_status', table_name='alerts')
    op.drop_index(op.f('ix_alerts_instrument_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_exchange_id'), table_name='alerts')
    op.create_index(op.f('ix_alerts_id'), 'alerts', ['id'], unique=False)
    op.alter_column('alerts', 'params',
               existing_type=mysql.JSON(),
               nullable=True)
    op.drop_column('alerts', 'updated_at')
    op.drop_column('alerts', 'timezone')
    op.drop_column('alerts', 'valid_to')
    op.drop_column('alerts', 'valid_from')
    op.drop_column('alerts', 'throttle_seconds')
    op.drop_column('alerts', 'instrument_id')
    op.drop_column('alerts', 'exchange_id')
    op.drop_column('alerts', 'scope')
    op.drop_index(op.f('ix_deliveries_user_channel_id'), table_name='deliveries')
    op.drop_index('ix_deliveries_status', table_name='deliveries')
    op.drop_index(op.f('ix_deliveries_alert_event_id'), table_name='deliveries')
    op.drop_table('deliveries')
    op.drop_index(op.f('ix_alert_events_instrument_id'), table_name='alert_events')
    op.drop_index(op.f('ix_alert_events_exchange_id'), table_name='alert_events')
    op.drop_index(op.f('ix_alert_events_alert_id'), table_name='alert_events')
    op.drop_index('ix_alert_events_alert_detected', table_name='alert_events')
    op.drop_table('alert_events')
    op.drop_index(op.f('ix_alert_channel_targets_user_channel_id'), table_name='alert_channel_targets')
    op.drop_index(op.f('ix_alert_channel_targets_alert_id'), table_name='alert_channel_targets')
    op.drop_table('alert_channel_targets')
    op.drop_index(op.f('ix_watchlist_items_user_id'), table_name='watchlist_items')
    op.drop_index(op.f('ix_watchlist_items_instrument_id'), table_name='watchlist_items')
    op.drop_index(op.f('ix_watchlist_items_exchange_id'), table_name='watchlist_items')
    op.drop_table('watchlist_items')
    op.drop_index(op.f('ix_user_identities_user_id'), table_name='user_identities')
    op.drop_table('user_identities')
    op.drop_index(op.f('ix_user_channels_user_id'), table_name='user_channels')
    op.drop_index('ix_user_channels_type', table_name='user_channels')
    op.drop_table('user_channels')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index('ix_sessions_expires', table_name='sessions')
    op.drop_table('sessions')
    op.drop_index('ix_prices_latest_ts', table_name='prices_latest')
    op.drop_index('ix_prices_latest_instrument', table_name='prices_latest')
    op.drop_table('prices_latest')
    op.drop_index('ix_price_1m_instr_bucket', table_name='price_snapshots_1m')
    op.drop_index('ix_price_1m_bucket', table_name='price_snapshots_1m')
    op.drop_table('price_snapshots_1m')
    op.drop_index(op.f('ix_password_resets_user_id'), table_name='password_resets')
    op.drop_table('password_resets')
    op.drop_index(op.f('ix_exchange_instruments_instrument_id'), table_name='exchange_instruments')
    op.drop_index(op.f('ix_exchange_instruments_exchange_symbol'), table_name='exchange_instruments')
    op.drop_index(op.f('ix_exchange_instruments_exchange_id'), table_name='exchange_instruments')
    op.drop_table('exchange_instruments')
    op.drop_table('instruments')
    op.drop_table('exchanges')
    # ### end Alembic commands ###
