"""alert_type table update

Revision ID: ce2a22d189c9
Revises: ee241b2ad235
Create Date: 2026-04-22 20:06:46.650077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce2a22d189c9'
down_revision: Union[str, Sequence[str], None] = 'ee241b2ad235'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alert_types', sa.Column('direction', sa.String(length=32), nullable=True))
    op.add_column('alert_types', sa.Column('form_type', sa.String(length=32), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alert_types', 'form_type')
    op.drop_column('alert_types', 'direction')
    # ### end Alembic commands ###
