"""add column config_fingerprint to user_channels table 

Revision ID: cfdac8173e10
Revises: 78438be647e9
Create Date: 2025-10-04 18:33:46.913910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfdac8173e10'
down_revision: Union[str, Sequence[str], None] = '78438be647e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_channels', sa.Column('config_fingerprint', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_user_channels_config_fingerprint'), 'user_channels', ['config_fingerprint'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_channels_config_fingerprint'), table_name='user_channels')
    op.drop_column('user_channels', 'config_fingerprint')
    # ### end Alembic commands ###
