"""rev_000X: schema sync with 20250918 DDL

Revision ID: d390f9becff0
Revises: ca47ead8f7a5
Create Date: 2025-09-19 15:30:14.190733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd390f9becff0'
down_revision: Union[str, Sequence[str], None] = 'ca47ead8f7a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
