"""alert_types 테이블 추가, alerts 테이블 변경(alert_type_id, is_once 추가, type 제거)

Revision ID: d7ed04ae0055
Revises: 6ec582a52d70
Create Date: 2026-02-15 17:42:09.565406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd7ed04ae0055'
down_revision: Union[str, Sequence[str], None] = '6ec582a52d70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.add_column('alerts', sa.Column('alert_type_id', sa.Integer(), nullable=False))
    op.add_column('alerts', sa.Column('is_once', sa.Boolean(), server_default=sa.text('1'), nullable=False))
    op.drop_index(op.f('ix_alerts_type'), table_name='alerts')
    op.create_index(op.f('ix_alerts_alert_type_id'), 'alerts', ['alert_type_id'], unique=False)
    op.create_foreign_key(None, 'alerts', 'alert_types', ['alert_type_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('alerts', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('type', mysql.ENUM('price', 'pct_change', 'volume', 'ma_cross', 'spread', collation='utf8mb4_unicode_ci'), nullable=False))
    op.drop_constraint(None, 'alerts', type_='foreignkey')
    op.drop_index(op.f('ix_alerts_alert_type_id'), table_name='alerts')
    op.create_index(op.f('ix_alerts_type'), 'alerts', ['type'], unique=False)
    op.drop_column('alerts', 'is_once')
    op.drop_column('alerts', 'alert_type_id')
    op.drop_table('alert_types')
    # ### end Alembic commands ###
