"""update news rss tables

Revision ID: d9facab3463a
Revises: 5efae499d9c2
Create Date: 2026-05-19 00:29:55.256683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9facab3463a'
down_revision: Union[str, Sequence[str], None] = '5efae499d9c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rss_providers', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('rss_sources', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rss_sources', 'deleted_at')
    op.drop_column('rss_providers', 'deleted_at')
    # ### end Alembic commands ###
