"""refresh

Revision ID: dca0cdcbc567
Revises: 31d48e0d51fe
Create Date: 2025-10-13 15:12:12.046155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'dca0cdcbc567'
down_revision: Union[str, Sequence[str], None] = '31d48e0d51fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outboxs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('aggregate_id', sa.BigInteger(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'sending', 'sent', 'failed', name='outbox_status', create_constraint=True), server_default='pending', nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('outbox')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outbox',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('event_type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('aggregate_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('payload', mysql.JSON(), nullable=False),
    sa.Column('status', mysql.ENUM('pending', 'sending', 'sent', 'failed'), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('attempts', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('next_run_at', mysql.DATETIME(), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('outboxs')
    # ### end Alembic commands ###
