"""alert clear

Revision ID: e118eb84799e
Revises: ce2a22d189c9
Create Date: 2026-04-28 17:45:37.350920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e118eb84799e'
down_revision: Union[str, Sequence[str], None] = 'ce2a22d189c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('uq_alerts_user_name'), table_name='alerts')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('uq_alerts_user_name'), 'alerts', ['user_id', 'name'], unique=True)
    # ### end Alembic commands ###
