"""add exchange_instrument_tickers table for 24h ticker stats

Revision ID: e37191c399a6
Revises: 4c1a871d383f
Create Date: 2026-03-15 19:50:45.584056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e37191c399a6'
down_revision: Union[str, Sequence[str], None] = '4c1a871d383f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchange_instrument_tickers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exchange_instrument_id', sa.Integer(), nullable=False),
    sa.Column('last_price', sa.DECIMAL(precision=32, scale=16), nullable=False),
    sa.Column('high_24h', sa.DECIMAL(precision=32, scale=16), nullable=False),
    sa.Column('low_24h', sa.DECIMAL(precision=32, scale=16), nullable=False),
    sa.Column('volume_24h', sa.DECIMAL(precision=32, scale=16), nullable=False),
    sa.Column('price_change_24h', sa.DECIMAL(precision=32, scale=16), nullable=False),
    sa.Column('price_change_rate_24h', sa.DECIMAL(precision=32, scale=16), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['exchange_instrument_id'], ['exchange_instruments.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exchange_instrument_id', name='uq_ticker_exchange_instrument')
    )
    op.create_index(op.f('ix_exchange_instrument_tickers_exchange_instrument_id'), 'exchange_instrument_tickers', ['exchange_instrument_id'], unique=False)
    op.create_index('ix_ticker_exchange_instrument', 'exchange_instrument_tickers', ['exchange_instrument_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ticker_exchange_instrument', table_name='exchange_instrument_tickers')
    op.drop_index(op.f('ix_exchange_instrument_tickers_exchange_instrument_id'), table_name='exchange_instrument_tickers')
    op.drop_table('exchange_instrument_tickers')
    # ### end Alembic commands ###
