"""update news rss tables

Revision ID: e54a225d4d81
Revises: d9facab3463a
Create Date: 2026-05-19 00:31:46.477245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e54a225d4d81'
down_revision: Union[str, Sequence[str], None] = 'd9facab3463a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_item_stats', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('news_item_translations', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('news_items', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news_items', 'deleted_at')
    op.drop_column('news_item_translations', 'deleted_at')
    op.drop_column('news_item_stats', 'deleted_at')
    # ### end Alembic commands ###
