"""unify sort_order naming and update user_channels schema

Revision ID: e61a4a39387a
Revises: 9fffc028c249
Create Date: 2026-04-17 19:09:09.652670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e61a4a39387a'
down_revision: Union[str, Sequence[str], None] = '9fffc028c249'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('faqs', sa.Column('sort_order', sa.Integer(), nullable=False))
    op.drop_column('faqs', 'display_order')
    op.add_column('user_channels', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user_channels', sa.Column('is_active', sa.Boolean(), server_default=sa.text('0'), nullable=False))
    op.drop_column('user_channels', 'is_default')
    op.drop_column('user_channels', 'is_deleted')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_channels', sa.Column('is_deleted', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False))
    op.add_column('user_channels', sa.Column('is_default', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.drop_column('user_channels', 'is_active')
    op.drop_column('user_channels', 'deleted_at')
    op.add_column('faqs', sa.Column('display_order', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('faqs', 'sort_order')
    # ### end Alembic commands ###
