"""change watchlist_items index to unique constraint on (user_id, exchange_instrument_id)

Revision ID: e8badc44a9ae
Revises: e37191c399a6
Create Date: 2026-03-15 19:57:58.316135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8badc44a9ae'
down_revision: Union[str, Sequence[str], None] = 'e37191c399a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_wi_user_exchange_instrument', 'watchlist_items', ['user_id', 'exchange_instrument_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_wi_user_exchange_instrument', 'watchlist_items', type_='unique')
    # ### end Alembic commands ###
