"""alerts, alert_events, alert_types 테이블 변경

Revision ID: ee241b2ad235
Revises: 02a6b92df221
Create Date: 2026-04-21 18:15:18.342843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ee241b2ad235'
down_revision: Union[str, Sequence[str], None] = '02a6b92df221'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alert_events', 'dedup_key',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64),
               nullable=False)
    op.add_column('alert_types', sa.Column('indicator', sa.String(length=32), nullable=False))
    op.add_column('alert_types', sa.Column('param_schema', sa.JSON(), nullable=False))
    op.add_column('alert_types', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('alert_types', 'is_deleted')
    op.drop_column('alert_types', 'params')
    op.add_column('alerts', sa.Column('timeframe', sa.String(length=16), nullable=True))
    op.add_column('alerts', sa.Column('period', sa.Integer(), nullable=True))
    op.add_column('alerts', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('alerts', 'is_deleted')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('is_deleted', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False))
    op.drop_column('alerts', 'deleted_at')
    op.drop_column('alerts', 'period')
    op.drop_column('alerts', 'timeframe')
    op.add_column('alert_types', sa.Column('params', mysql.JSON(), nullable=False))
    op.add_column('alert_types', sa.Column('is_deleted', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False))
    op.drop_column('alert_types', 'deleted_at')
    op.drop_column('alert_types', 'param_schema')
    op.drop_column('alert_types', 'indicator')
    op.alter_column('alert_events', 'dedup_key',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64),
               nullable=True)
    # ### end Alembic commands ###
