"""schema: alert_events를 exchange_instrument_id NULL FK로 전환, alert_id는 RESTRICT로 유지(소프트 삭제 정책)

Revision ID: f4706728b70c
Revises: 339e8141ec1a
Create Date: 2025-09-25 21:10:52.900389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4706728b70c'
down_revision: Union[str, Sequence[str], None] = '339e8141ec1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
