"""exchange_instruments table add column tick_size

Revision ID: f5737b7490c3
Revises: e118eb84799e
Create Date: 2026-05-03 18:42:12.748474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5737b7490c3'
down_revision: Union[str, Sequence[str], None] = 'e118eb84799e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exchange_instruments', sa.Column('tick_size', sa.DECIMAL(precision=20, scale=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exchange_instruments', 'tick_size')
    # ### end Alembic commands ###
