"""email_verifications.sent_at null 허용

Revision ID: fe63fdb7ea7a
Revises: 55f6f80c522a
Create Date: 2025-11-17 17:37:46.436071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'fe63fdb7ea7a'
down_revision: Union[str, Sequence[str], None] = '55f6f80c522a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('email_verifications', 'sent_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('email_verifications', 'sent_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###
