from typing import Protocol, Sequence
from app.infra.db.model import UserChannelModel

class ChannelRepo(Protocol): 
    def list_channels_by_user_id(self, user_id: int) -> Sequence[UserChannelModel]: ...
    def get_by_channel_id(self, user_channel_id: int) -> UserChannelModel | None: ...
    def get_channel_cnt(
        self, *, user_id: int, provider_id: int,
    ) -> int | None: ...
    def get_channel_by_fingerprint(
        self, *, user_id: int, provider_id: int, fingerprint: str
    ) -> UserChannelModel: ...
    def add_channel(self, row: UserChannelModel) -> None: ...