from typing import Protocol, Sequence
from app.infra.db.model import UserChannelModel

class ChannelRepo(Protocol): 
    def list_by_user(self, user_id: int) -> Sequence[UserChannelModel]: ...
    def get_by_id(self, user_channel_id: int) -> UserChannelModel | None: ...
    def find_one_by_provider_id(
        self, *, user_id: int, provider_id: int
    ) -> UserChannelModel | None: ...
    def find_one_by_channel_cnt(
        self, *, user_id: int, provider_id: int,
    ) -> int | None: ...
    def find_one_by_fingerprint(
        self, *, user_id: int, provider_id: int, fingerprint: str
    ) -> UserChannelModel: ...
    def add(self, row: UserChannelModel) -> None: ...