from typing import Protocol, Optional, Sequence
from app.infra.db.model import ChannelProviderModel

class ProviderRepo(Protocol):
    def get_by_id(self, provider_id: int) -> Optional[ChannelProviderModel]: ...
    def get_by_code(self, code: str) -> Optional[ChannelProviderModel]: ...
    def list_active(self) -> Sequence[ChannelProviderModel]: ...
