from typing import Protocol
from app.infra.db.model import UserModel, EmailVerificationModel

class UserRepo(Protocol):

    def add_user(self, user: UserModel) -> UserModel: ...
    def add_email_verification(self, email_verification: EmailVerificationModel) -> EmailVerificationModel: ...
    def get_user_by_email_fingerprint(self, email_fingerprint: bytes) -> UserModel | None: ...
    def get_by_user_id(self, user_id: int) -> UserModel | None: ...
    def get_email_verification_by_id(self, email_verification_id: int) -> EmailVerificationModel | None: ...
    def get_email_verification_by_token_hash(self, token_hash: bytes) -> EmailVerificationModel | None: ...
    def list_users_filter(self, *, status: str | None, role: str | None, limit: int, offset: int) -> list[UserModel]: ...