from typing import Protocol
from app.infra.db.model import UserModel

class UserRepo(Protocol):

    def add_user(self, user: UserModel) -> UserModel: ...
    def get_user_by_email(self, email: str) -> UserModel | None: ...
    def get_by_user_id(self, user_id: int) -> UserModel | None: ...
    def list_users_filter(self, *, status: str | None, role: str | None, limit: int, offset: int) -> list[UserModel]: ...