name: Deploy Frontend Prod

on:
  workflow_dispatch:

concurrency:
  group: deploy-frontend-prod
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  deploy:
    uses: ./.github/workflows/reusable-deploy-frontend-swa.yml
    with:
      environment: prod
      build_command: npm run build:prod
      app_location: frontend/dist