name: Deploy Backend Prod

on:
  workflow_dispatch:

concurrency:
  group: deploy-backend-prod
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  deploy:
    uses: ./.github/workflows/reusable-deploy-backend.yml
    with:
      environment: prod
      dockerfile_name: Dockerfile.prod
      runner_label: mah-prod-vm
    secrets: inherit
