name: Deploy Frontend Dev

on:
  workflow_dispatch:

concurrency:
  group: deploy-frontend-dev
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  deploy:
    uses: ./.github/workflows/reusable-deploy-frontend-swa.yml
    with:
      environment: dev
      build_command: npm run build:dev
      app_location: frontend/dist